"""
GRAM-DISHA — Geographic & Urbanity Reference Data Store
Smart India Hackathon 2026 (Team ERGON)
Master structured repository for 28 States and 8 Union Territories with comprehensive
district records, LGD codes, urbanity classification, RBI tiers, ODOP, and ACZs.
"""

from typing import List, Dict, Any, Optional
from app.domains.geography.schemas import (
    TerritoryType,
    UrbanityClassification,
    RBITierClassification,
    VerificationStatus,
    ValueState,
    DatasetRegistryEntry,
    ProvenanceInfo,
    DistrictRecord,
    StateReference,
    DataConflictRecord,
)

# -------------------------------------------------------------------------
# DATASET REGISTRY & PROVENANCE METADATA
# -------------------------------------------------------------------------

DATASET_REGISTRY = DatasetRegistryEntry(
    dataset_id="district_urbanity_policy_reference",
    dataset_name="Gram-Disha India District Urbanity Reference With UTs",
    human_readable_name="Gram-Disha India District Urbanity Reference With UTs",
    category="Geographic + Policy Reference Dataset",
    scope="India",
    geographic_levels=["State", "District"],
    primary_purpose=(
        "Administrative validation, Urbanity classification, PMEGP geographic "
        "differentiation context, ODOP alignment, RBI tier contextualization, "
        "Feasibility analysis, Hyper-local analytical context"
    ),
    source_document="Gram-Disha_India_District_Urbanity_Reference_With_UTs-2.docx",
    source_authority="Ministry of Panchayati Raj (MoPR), KVIC/MoMSME, MoFPI, RBI, ORGI",
    source_url="https://lgdirectory.gov.in/",
    version="1.0.0",
    data_vintage="2025-2026",
    ingestion_date="2026-03-01T00:00:00Z",
    verification_date="2026-03-01T00:00:00Z",
    geographic_scope="28 States and 8 Union Territories (~788+ Districts)",
    geographic_level="DISTRICT",
    record_count=788,
    status=VerificationStatus.PROVISIONAL,
    confidence=0.95,
    notes="Primary geographic reference dataset for Gram-Disha decision intelligence engine.",
)

PROVENANCE_METADATA = ProvenanceInfo(
    source_id="SRC_LGD_01",
    source_name="Local Government Directory (LGD) & National Policy Registers",
    source_authority="Ministry of Panchayati Raj, KVIC, MoFPI, RBI, ORGI",
    source_url="https://lgdirectory.gov.in/",
    source_document="Gram-Disha_India_District_Urbanity_Reference_With_UTs-2.docx",
    source_version="1.0.0",
    data_vintage="2025-2026",
    ingestion_timestamp="2026-03-01T00:00:00Z",
    verification_timestamp="2026-03-01T00:00:00Z",
    geographic_level="DISTRICT",
    verification_status=VerificationStatus.PROVISIONAL,
    confidence=0.95,
    notes="Traceable to official MoPR, KVIC, MoFPI, RBI and Census gazettes.",
)

# -------------------------------------------------------------------------
# 28 STATES AND 8 UNION TERRITORIES REGISTRY
# -------------------------------------------------------------------------

STATES_REGISTRY: List[StateReference] = [
    # 28 States
    StateReference(state_lgd_code="28", state_name="Andhra Pradesh", territory_type=TerritoryType.STATE, total_districts=26),
    StateReference(state_lgd_code="12", state_name="Arunachal Pradesh", territory_type=TerritoryType.STATE, total_districts=26),
    StateReference(state_lgd_code="18", state_name="Assam", territory_type=TerritoryType.STATE, total_districts=35),
    StateReference(state_lgd_code="10", state_name="Bihar", territory_type=TerritoryType.STATE, total_districts=38),
    StateReference(state_lgd_code="22", state_name="Chhattisgarh", territory_type=TerritoryType.STATE, total_districts=33),
    StateReference(state_lgd_code="30", state_name="Goa", territory_type=TerritoryType.STATE, total_districts=2),
    StateReference(state_lgd_code="24", state_name="Gujarat", territory_type=TerritoryType.STATE, total_districts=33),
    StateReference(state_lgd_code="06", state_name="Haryana", territory_type=TerritoryType.STATE, total_districts=22),
    StateReference(state_lgd_code="02", state_name="Himachal Pradesh", territory_type=TerritoryType.STATE, total_districts=12),
    StateReference(state_lgd_code="20", state_name="Jharkhand", territory_type=TerritoryType.STATE, total_districts=24),
    StateReference(state_lgd_code="29", state_name="Karnataka", territory_type=TerritoryType.STATE, total_districts=31),
    StateReference(state_lgd_code="32", state_name="Kerala", territory_type=TerritoryType.STATE, total_districts=14),
    StateReference(state_lgd_code="23", state_name="Madhya Pradesh", territory_type=TerritoryType.STATE, total_districts=55),
    StateReference(state_lgd_code="27", state_name="Maharashtra", territory_type=TerritoryType.STATE, total_districts=36),
    StateReference(state_lgd_code="14", state_name="Manipur", territory_type=TerritoryType.STATE, total_districts=16),
    StateReference(state_lgd_code="17", state_name="Meghalaya", territory_type=TerritoryType.STATE, total_districts=12),
    StateReference(state_lgd_code="15", state_name="Mizoram", territory_type=TerritoryType.STATE, total_districts=11),
    StateReference(state_lgd_code="13", state_name="Nagaland", territory_type=TerritoryType.STATE, total_districts=16),
    StateReference(state_lgd_code="21", state_name="Odisha", territory_type=TerritoryType.STATE, total_districts=30),
    StateReference(state_lgd_code="03", state_name="Punjab", territory_type=TerritoryType.STATE, total_districts=23),
    StateReference(state_lgd_code="08", state_name="Rajasthan", territory_type=TerritoryType.STATE, total_districts=50),
    StateReference(state_lgd_code="11", state_name="Sikkim", territory_type=TerritoryType.STATE, total_districts=6),
    StateReference(state_lgd_code="33", state_name="Tamil Nadu", territory_type=TerritoryType.STATE, total_districts=38),
    StateReference(state_lgd_code="36", state_name="Telangana", territory_type=TerritoryType.STATE, total_districts=33),
    StateReference(state_lgd_code="16", state_name="Tripura", territory_type=TerritoryType.STATE, total_districts=8),
    StateReference(state_lgd_code="09", state_name="Uttar Pradesh", territory_type=TerritoryType.STATE, total_districts=75),
    StateReference(state_lgd_code="05", state_name="Uttarakhand", territory_type=TerritoryType.STATE, total_districts=13),
    StateReference(state_lgd_code="19", state_name="West Bengal", territory_type=TerritoryType.STATE, total_districts=23),
    # 8 Union Territories
    StateReference(state_lgd_code="35", state_name="Andaman and Nicobar Islands", territory_type=TerritoryType.UNION_TERRITORY, total_districts=3),
    StateReference(state_lgd_code="04", state_name="Chandigarh", territory_type=TerritoryType.UNION_TERRITORY, total_districts=1),
    StateReference(state_lgd_code="26", state_name="Dadra and Nagar Haveli and Daman and Diu", territory_type=TerritoryType.UNION_TERRITORY, total_districts=3),
    StateReference(state_lgd_code="07", state_name="Delhi", territory_type=TerritoryType.UNION_TERRITORY, total_districts=11),
    StateReference(state_lgd_code="01", state_name="Jammu and Kashmir", territory_type=TerritoryType.UNION_TERRITORY, total_districts=20),
    StateReference(state_lgd_code="37", state_name="Ladakh", territory_type=TerritoryType.UNION_TERRITORY, total_districts=2),
    StateReference(state_lgd_code="31", state_name="Lakshadweep", territory_type=TerritoryType.UNION_TERRITORY, total_districts=1),
    StateReference(state_lgd_code="34", state_name="Puducherry", territory_type=TerritoryType.UNION_TERRITORY, total_districts=4),
]

# -------------------------------------------------------------------------
# STRUCTURED DISTRICT RECORDS (INGESTED & NORMALIZED)
# -------------------------------------------------------------------------

DISTRICT_RECORDS: List[DistrictRecord] = [
    # Maharashtra (27)
    DistrictRecord(
        state_lgd_code="27",
        state_name="Maharashtra",
        district_lgd_code="489",
        district_name="Yavatmal",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=78.4,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Cotton Ginning & Processing / Soybean Oil",
        agro_climatic_zone="Western Plateau & Hill Region (Zone IX)",
        power_tariff_zone="MSEDCL Zone 4 Rural Feeder (Subsidized Agro Rate)",
        power_subsidies="Agro-Processing & Rural Micro-Enterprise Tariff Support",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.98,
        notes="High rurality district with strong cotton/soybean cluster.",
        gram_disha_primary_scope=True,
    ),
    DistrictRecord(
        state_lgd_code="27",
        state_name="Maharashtra",
        district_lgd_code="488",
        district_name="Wardha",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=67.5,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Organic Cotton Khadi / Spices",
        agro_climatic_zone="Western Plateau & Hill Region (Zone IX)",
        power_tariff_zone="MSEDCL Wardha Semi-Urban Feeder",
        power_subsidies="Rural Artisanal Khadi Subsidized Power",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        gram_disha_primary_scope=True,
    ),
    DistrictRecord(
        state_lgd_code="27",
        state_name="Maharashtra",
        district_lgd_code="478",
        district_name="Nagpur",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.URBAN,
        census_rural_percentage=31.7,
        rbi_tier_classification=RBITierClassification.TIER_1,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Nagpur Mandarin Orange Processing",
        agro_climatic_zone="Eastern Plateau & Hills (Zone VII)",
        power_tariff_zone="MSEDCL Industrial Zone 1",
        power_subsidies="General MSME Tariff Rate",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.98,
        gram_disha_primary_scope=False,
    ),
    DistrictRecord(
        state_lgd_code="27",
        state_name="Maharashtra",
        district_lgd_code="491",
        district_name="Pune",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.METROPOLITAN,
        census_rural_percentage=38.9,
        rbi_tier_classification=RBITierClassification.TIER_1,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Pomegranate / Engineering Components",
        agro_climatic_zone="Western Ghats & Coastal Zone",
        power_tariff_zone="MSEDCL Metro Industrial Feed",
        power_subsidies="Standard Industrial Tariff",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.98,
        gram_disha_primary_scope=False,
    ),
    # Uttar Pradesh (09)
    DistrictRecord(
        state_lgd_code="09",
        state_name="Uttar Pradesh",
        district_lgd_code="175",
        district_name="Varanasi",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=56.6,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Banarasi Silk Weaving & Handloom / Zardozi",
        agro_climatic_zone="Middle Gangetic Plain (Zone IV)",
        power_tariff_zone="UPPCL Rural-Peri-Urban Feeder",
        power_subsidies="Weaver Subsidized Power Scheme",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.98,
        gram_disha_primary_scope=True,
    ),
    DistrictRecord(
        state_lgd_code="09",
        state_name="Uttar Pradesh",
        district_lgd_code="144",
        district_name="Gorakhpur",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=81.2,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Terracotta Clay Crafts / Readymade Garments",
        agro_climatic_zone="Middle Gangetic Plain (Zone IV)",
        power_tariff_zone="UPPCL Purvanchal Rural Feeder",
        power_subsidies="Rural Craft Artisan Tariff Exemption",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.97,
        gram_disha_primary_scope=True,
    ),
    DistrictRecord(
        state_lgd_code="09",
        state_name="Uttar Pradesh",
        district_lgd_code="160",
        district_name="Mirzapur",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=86.0,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Handmade Woolen Carpets & Dari",
        agro_climatic_zone="Middle Gangetic Plain (Zone IV)",
        power_tariff_zone="UPPCL Rural Vindhyachal Feeder",
        power_subsidies="Artisan Subsidized Power Tariff",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.97,
        gram_disha_primary_scope=True,
    ),
    # Rajasthan (08)
    DistrictRecord(
        state_lgd_code="08",
        state_name="Rajasthan",
        district_lgd_code="112",
        district_name="Jodhpur",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=65.7,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Wooden Furniture & Handicrafts / Spices",
        agro_climatic_zone="Western Dry Region (Zone XIV)",
        power_tariff_zone="JVVNL Rural Feeder",
        power_subsidies="Solar Micro-Grid & Handicraft Incentive",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        gram_disha_primary_scope=True,
    ),
    DistrictRecord(
        state_lgd_code="08",
        state_name="Rajasthan",
        district_lgd_code="118",
        district_name="Nagaur",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=80.7,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Kasuri Methi (Fenugreek) / Hand Tools",
        agro_climatic_zone="Trans-Gangetic Plain / Western Dry Region",
        power_tariff_zone="JVVNL Rural Agro Feeder",
        power_subsidies="Agro-Processing Electric Subsidy",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        gram_disha_primary_scope=True,
    ),
    # Bihar (10)
    DistrictRecord(
        state_lgd_code="10",
        state_name="Bihar",
        district_lgd_code="208",
        district_name="Muzaffarpur",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=90.1,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Shahi Litchi Processing & Pulping / Lac Bangles",
        agro_climatic_zone="Middle Gangetic Plain (Zone IV)",
        power_tariff_zone="NBPDCL Rural Feeder",
        power_subsidies="Bihar Industrial Investment Promotion Subsidies",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.97,
        gram_disha_primary_scope=True,
    ),
    DistrictRecord(
        state_lgd_code="10",
        state_name="Bihar",
        district_lgd_code="210",
        district_name="Nalanda",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=84.1,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Hydroponic Greens / Khaja Sweet / Bamboo Craft",
        agro_climatic_zone="Middle Gangetic Plain (Zone IV)",
        power_tariff_zone="SBPDCL Nalanda Rural Grid",
        power_subsidies="Kisan Vidyut Subsidized Line",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        gram_disha_primary_scope=True,
    ),
    # Madhya Pradesh (23)
    DistrictRecord(
        state_lgd_code="23",
        state_name="Madhya Pradesh",
        district_lgd_code="435",
        district_name="Ujjain",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=60.8,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Batik Print Textiles / Poha (Flattened Rice)",
        agro_climatic_zone="Central Plateau & Hill Region (Zone VIII)",
        power_tariff_zone="MPWZ Ujjain Rural Feeder",
        power_subsidies="Rural Industrial Subsidized Unit Rate",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        gram_disha_primary_scope=True,
    ),
    # Gujarat (24)
    DistrictRecord(
        state_lgd_code="24",
        state_name="Gujarat",
        district_lgd_code="444",
        district_name="Anand",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=69.6,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Dairy Products & Milk Processing / Banana",
        agro_climatic_zone="Gujarat Plains & Hills Region (Zone XIII)",
        power_tariff_zone="MGVCL Agro Feeder",
        power_subsidies="Jyotigram Yojana Continuous Power Support",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.98,
        gram_disha_primary_scope=True,
    ),
    # Karnataka (29)
    DistrictRecord(
        state_lgd_code="29",
        state_name="Karnataka",
        district_lgd_code="535",
        district_name="Dharwad",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=43.2,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Dharwad Pedha & Food Processing / Navalagund Durries",
        agro_climatic_zone="Southern Plateau & Hills Region (Zone X)",
        power_tariff_zone="HESCOM Semi-Urban Feeder",
        power_subsidies="K-BITS Rural Startup Power Concessions",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        gram_disha_primary_scope=True,
    ),
    # Tamil Nadu (33)
    DistrictRecord(
        state_lgd_code="33",
        state_name="Tamil Nadu",
        district_lgd_code="582",
        district_name="Madurai",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=39.2,
        rbi_tier_classification=RBITierClassification.TIER_1,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Madurai Malli (Jasmine) Essential Oil / Sungudi Sarees",
        agro_climatic_zone="East Coast Plains & Hills (Zone XI)",
        power_tariff_zone="TANGEDCO Agro Industrial Feeder",
        power_subsidies="Cottage Industry Subsidized Tariff",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.97,
        gram_disha_primary_scope=True,
    ),
    # Assam (18)
    DistrictRecord(
        state_lgd_code="18",
        state_name="Assam",
        district_lgd_code="294",
        district_name="Kamrup Rural",
        territory_type=TerritoryType.STATE,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=90.6,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 35.0, "urban_general_pct": 25.0, "urban_special_pct": 35.0},
        notified_odop_commodity="Muga Silk & Eri Silk Weaving / Spices",
        agro_climatic_zone="Eastern Himalayan Region (Zone II)",
        power_tariff_zone="APDCL Rural North Bank Feeder",
        power_subsidies="Special Category NE MSME Power Rebate",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        notes="Special Category State / North Eastern subsidy rates apply under PMEGP.",
        gram_disha_primary_scope=True,
    ),
    # Union Territory: Jammu and Kashmir (01)
    DistrictRecord(
        state_lgd_code="01",
        state_name="Jammu and Kashmir",
        district_lgd_code="001",
        district_name="Anantnag",
        territory_type=TerritoryType.UNION_TERRITORY,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=73.8,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 35.0, "urban_general_pct": 25.0, "urban_special_pct": 35.0},
        notified_odop_commodity="Trout Fish Farming & Processing / Cricket Bats (Willow)",
        agro_climatic_zone="Western Himalayan Region (Zone I)",
        power_tariff_zone="KPDCL Kashmir Rural Grid",
        power_subsidies="Hill Area & Special UT Industrial Package",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.95,
        notes="Hill Area and Special Union Territory category subsidy rules.",
        gram_disha_primary_scope=True,
    ),
    # Union Territory: Ladakh (37)
    DistrictRecord(
        state_lgd_code="37",
        state_name="Ladakh",
        district_lgd_code="009",
        district_name="Leh",
        territory_type=TerritoryType.UNION_TERRITORY,
        urbanity_classification=UrbanityClassification.RURAL,
        census_rural_percentage=66.0,
        rbi_tier_classification=RBITierClassification.TIER_4,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 35.0, "urban_general_pct": 25.0, "urban_special_pct": 35.0},
        notified_odop_commodity="Seabuckthorn Berry Processing / Pashmina Wool",
        agro_climatic_zone="Western Himalayan High Altitude Cold Desert",
        power_tariff_zone="Ladakh Power Dev Dept Hydro/Solar Grid",
        power_subsidies="Cold Desert Special Development Subsidies",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.95,
        notes="High altitude border area special assistance.",
        gram_disha_primary_scope=True,
    ),
    # Union Territory: Delhi (07)
    DistrictRecord(
        state_lgd_code="07",
        state_name="Delhi",
        district_lgd_code="088",
        district_name="South West Delhi",
        territory_type=TerritoryType.UNION_TERRITORY,
        urbanity_classification=UrbanityClassification.METROPOLITAN,
        census_rural_percentage=6.4,
        rbi_tier_classification=RBITierClassification.TIER_1,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Bakery & Food Packaging / Light Engineering",
        agro_climatic_zone="Trans-Gangetic Plain (Zone VI)",
        power_tariff_zone="BSES Rajdhani Metro Feeder",
        power_subsidies="UNKNOWN",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.98,
        gram_disha_primary_scope=False,
    ),
    # Union Territory: Puducherry (34)
    DistrictRecord(
        state_lgd_code="34",
        state_name="Puducherry",
        district_lgd_code="601",
        district_name="Puducherry",
        territory_type=TerritoryType.UNION_TERRITORY,
        urbanity_classification=UrbanityClassification.URBAN,
        census_rural_percentage=31.7,
        rbi_tier_classification=RBITierClassification.TIER_2,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 25.0, "urban_general_pct": 15.0, "urban_special_pct": 25.0},
        notified_odop_commodity="Marine Products & Fish Processing / Leather Goods",
        agro_climatic_zone="East Coast Plains & Hills (Zone XI)",
        power_tariff_zone="Puducherry Electricity Dept Coastal Feeder",
        power_subsidies="UT Coastal Micro-Enterprise Rebate",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.96,
        gram_disha_primary_scope=False,
    ),
    # Union Territory: Andaman and Nicobar Islands (35)
    DistrictRecord(
        state_lgd_code="35",
        state_name="Andaman and Nicobar Islands",
        district_lgd_code="602",
        district_name="South Andaman",
        territory_type=TerritoryType.UNION_TERRITORY,
        urbanity_classification=UrbanityClassification.SEMI_URBAN_PERI_URBAN,
        census_rural_percentage=44.1,
        rbi_tier_classification=RBITierClassification.TIER_3,
        pmegp_subsidy_eligibility={"special_rural_pct": 35.0, "general_rural_pct": 35.0, "urban_general_pct": 25.0, "urban_special_pct": 35.0},
        notified_odop_commodity="Virgin Coconut Oil & Processing / Marine Fisheries",
        agro_climatic_zone="Island Region (Zone XV)",
        power_tariff_zone="A&N Electricity Dept Port Blair Feeder",
        power_subsidies="Island Special Category Subsidy",
        verification_status=VerificationStatus.VERIFIED,
        confidence=0.95,
        notes="Island territory special category subsidy rules.",
        gram_disha_primary_scope=True,
    ),
]

# -------------------------------------------------------------------------
# CONFLICT REGISTRY (FOR AUDIT & HUMAN VERIFICATION)
# -------------------------------------------------------------------------

DATA_CONFLICTS: List[DataConflictRecord] = []
