"""
Part 1: Southern Region & Southern UTs
- Tamil Nadu (38)
- Andhra Pradesh (26)
- Telangana (33)
- Karnataka (31)
- Kerala (14)
- Puducherry (4)
- Lakshadweep (1)
- Andaman and Nicobar Islands (3)
Total: 150 districts
"""

def get_south_data(format_district):
    states = []

    # 1. TAMIL NADU (38)
    tn_districts = [
        format_district(602, "Ariyalur", "RURAL", 89.0, "TIER_4", "Cashew Processing & Roasted Kernels / Lime", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Distribution Feeder", ["Ariyalur", "Sendurai", "Udayarpalayam", "Andimadam", "Jayankondam", "T.Palur", "Thirumanur"], ["Valajanagaram", "Subbrayapuram", "Kallankurichi", "Thirumanur"], 621704),
        format_district(726, "Chengalpattu", "SEMI_URBAN", 40.5, "TIER_2", "Automotive Engineering Components & Marine Fisheries", "ENGINEERING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Industrial & Peri-Urban Feeder", ["Chengalpattu", "Kattankulathur", "Maduranthakam", "St. Thomas Mount", "Tiruporur", "Lathur", "Chithamur", "Acharapakkam", "Tirukalukundram", "Cheyyur", "Tambaram", "Pallavaram", "Vandalur"], ["Acharapakkam", "Nemmeli", "Kelambakkam", "Kovalam", "Vandalur"], 603104),
        format_district(603, "Chennai", "METROPOLITAN", 0.0, "TIER_1", "Leather Goods, Footwear & IT / SaaS Solutions", "LEATHER_IT", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Metro Priority Grid (24x7)", ["Egmore", "Guindy", "Mylapore", "Tondiarpet", "Velachery", "Ambattur", "Alandur", "Aminjikarai", "Ayanavaram", "Mambalam", "Madhavaram", "Perambur", "Purasawalkam", "Sholinganallur", "Thiruvottiyur"], ["Chennai Corporation Zone 1", "Chennai Corporation Zone 5", "Chennai Corporation Zone 10"], 600032),
        format_district(604, "Coimbatore", "SEMI_URBAN", 24.2, "TIER_1", "Pump Motors, Foundry Castings & Organic Coconut Coir", "ENGINEERING_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Coimbatore High Tension Feeder", ["Coimbatore North", "Coimbatore South", "Pollachi North", "Pollachi South", "Mettupalayam", "Sulur", "Annur", "Valparai", "Kinathukadavu", "Madukkarai", "Anamalai", "Perur", "Thondamuthur", "Karamadai", "Sultanpet", "S.S. Kulam"], ["Samathur", "Kinathukadavu", "Negamam", "Zamin Uthukuli", "Vellalore", "Periyanaickenpalayam"], 642123),
        format_district(605, "Cuddalore", "RURAL", 66.0, "TIER_3", "Cashew Nut Processing & Jackfruit Pulping", "AGRO_PROCESSING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Cuddalore Rural Feeder", ["Cuddalore", "Panruti", "Kurinjipadi", "Bhuvanagiri", "Kattumannarkoil", "Vridhachalam", "Kammapuram", "Mangalur", "Nallur", "Kumaratchi", "Keerapalayam", "Srimushnam", "Tittakudi"], ["Semakottai", "Marungur", "Melpattampakkam", "Thiruvathigai"], 607106),
        format_district(606, "Dharmapuri", "RURAL", 83.1, "TIER_4", "Mango Pulp Extraction & Finger Millet (Ragi) Value Addition", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Dharmapuri Agro Feeder", ["Dharmapuri", "Pennagaram", "Harur", "Palacode", "Karimangalam", "Morappur", "Pappireddipatti", "Nallampalli", "Kadathur", "Eriyur"], ["Kaveripattinam", "Indur", "Nallampalli", "Eriyur"], 636808),
        format_district(607, "Dindigul", "RURAL", 62.6, "TIER_3", "Dindigul Brass Locks & Nilakottai Cut Flowers / Gloriosa", "HANDICRAFTS_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Dindigul Rural Feeder", ["Dindigul", "Nilakottai", "Oddanchatram", "Palani", "Kodaikanal", "Athoor", "Batlagundu", "Natham", "Vedasandur", "Reddiarchatram", "Shanwarpatti", "Guziliamparai", "Thoppampatti", "Vadamadurai"], ["Pallapatti", "Siluvathur", "Vembarpatti", "Ayyalur"], 624208),
        format_district(608, "Erode", "SEMI_URBAN", 48.6, "TIER_2", "Turmeric Processing & Powerloom Bedspread Handlooms", "AGRO_TEXTILES", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Erode Industrial/Rural Feeder", ["Erode", "Bhavani", "Gobichettipalayam", "Perundurai", "Sathyamangalam", "Anthiyur", "Modakkurichi", "Kodumudi", "Nambiyur", "Thalavadi", "Bhavanisagar", "Ammapet", "Chennimalai", "T.N. Palayam"], ["Kalingarayanpalayam", "Gobi Rural", "Nambiyur", "Kavindapadi"], 638452),
        format_district(727, "Kallakurichi", "RURAL", 85.4, "TIER_4", "Sugarcane Jaggery & Rice Processing / Tapioca Sago", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Feeder", ["Kallakurichi", "Chinnasalem", "Sankarapuram", "Rishivandiyam", "Thirukovilur", "Ulundurpet", "Kalvarayan Hills", "Thiyagadurgam"], ["Kachirayapalayam", "Pakkaimedu", "Pottiyam", "Kariyalur"], 606201),
        format_district(609, "Kanchipuram", "SEMI_URBAN", 36.5, "TIER_2", "Kanchipuram Pure Mulberry Silk Sarees & Zari Weaving", "HANDLOOM_TEXTILE", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Kanchi Semi-Urban Feeder", ["Kanchipuram", "Walajabad", "Sriperumbudur", "Kundrathur", "Uthiramerur"], ["Orikkai", "Perunagar", "Manampathi", "Vada Illuppai"], 631502),
        format_district(610, "Kanyakumari", "SEMI_URBAN", 17.7, "TIER_2", "Natural Rubber Products & Cloves / Fish Processing", "AGRO_PROCESSING", "West Coast Plains and Ghats Region (Zone XII)", "TANGEDCO Coastal Grid Feeder", ["Agastheeswaram", "Rajakkamangalam", "Thovalai", "Kurunthancode", "Tuckalay", "Thiruvattar", "Killiyoor", "Munchirai", "Melpuram", "Vilavancode", "Kalkulam"], ["Suchindram", "Marthandam", "Colachel Rural", "Kadiapattanam"], 629165),
        format_district(611, "Karur", "SEMI_URBAN", 59.2, "TIER_3", "Home Textiles, Kitchen Linen & Mosquito Net Manufacture", "TEXTILES", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Karur Industrial Feeder", ["Karur", "Thanthoni", "Aravakurichi", "K.Paramathi", "Kulithalai", "Krishnarayapuram", "Kadavur", "Thogamalai"], ["Vengamedu", "Pallapatti", "Inungur", "Mayanur"], 639005),
        format_district(612, "Krishnagiri", "RURAL", 77.2, "TIER_3", "Commercial Mango Pulp Concentrates & Granite Carvings", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Krishnagiri Agro Feeder", ["Krishnagiri", "Hosur", "Bargur", "Kaveripattinam", "Pochampalli", "Uthangarai", "Mathur", "Shoolagiri", "Kelamangalam", "Thally", "Veppanapalli", "Denkanikottai", "Anchetti"], ["Kandikuppam", "Pannandur", "Biligundlu", "Royakottai"], 635108),
        format_district(613, "Madurai", "SEMI_URBAN", 39.2, "TIER_1", "Madurai Malli (Jasmine Flower) Perfume Extracts & Handloom Sungudi Sarees", "AGRO_TEXTILE", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Madurai Central Feeder", ["Madurai East", "Madurai West", "Thiruparankundram", "Melur", "Vadipatti", "Alanganallur", "Usilampatti", "Tirumangalam", "Chempatti", "Kottampatti", "Sedapatti", "T.Kallupatti", "Kallikudi"], ["Thirumogur", "Othakadai", "Alanganallur Rural", "Sholavandan"], 625501),
        format_district(728, "Mayiladuthurai", "RURAL", 78.5, "TIER_3", "Seafood Cold Chain Processing & Poompuhar Bronze Icons", "FISHERIES_HANDICRAFTS", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Coastal Rural Feeder", ["Mayiladuthurai", "Kuthalam", "Sirkazhi", "Sembanarkoil", "Kollidam", "Tharangambadi"], ["Poompuhar", "Tharangambadi", "Vaitheeswarankoil", "Manalmedu"], 609105),
        format_district(614, "Nagapattinam", "RURAL", 77.4, "TIER_3", "Marine Fish & Shrimp Processing / Salt Extraction", "FISHERIES", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Coastal Feeder", ["Nagapattinam", "Keelaiyur", "Kilvelur", "Thirumarugal", "Vedaranyam", "Thalainayar"], ["Velankanni Rural", "Vedaranyam Salt Flats", "Kodiyakarai", "Sikkal"], 614810),
        format_district(615, "Namakkal", "RURAL", 59.7, "TIER_3", "Poultry Layer Egg Products, Feed Mills & Rig Body Building", "POULTRY_ENGINEERING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Poultry Agro Feeder", ["Namakkal", "Rasipuram", "Tiruchengode", "Paramathi", "Kolli Hills", "Sendamangalam", "Mohanur", "Mallasamudram", "Elachipalayam", "Puduchatram", "Vennandur", "Erumaipatti", "Kabilarmalai"], ["Valavanthi Nadu", "Seerapalli", "Thindamangalam", "Nallipalayam"], 637211),
        format_district(616, "Nilgiris", "RURAL", 60.8, "TIER_3", "Orthodox Nilgiri Hill Tea & Eucalyptus Essential Oil", "AGRO_PLANTATION", "West Coast Plains and Ghats Region (Zone XII)", "TANGEDCO Hill Feeder", ["Udhagamandalam (Ooty)", "Coonoor", "Kotagiri", "Gudalur", "Kundah", "Pandalur"], ["Ketti", "Adigaratti", "Nedugula", "Hullathy"], 643217),
        format_district(617, "Perambalur", "RURAL", 82.8, "TIER_4", "Small Shallot Onion & Maize Starch Processing", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Agro Rural Feeder", ["Perambalur", "Veppanthattai", "Veppur", "Alathur"], ["Chettikulam", "Kurumbalur", "Valikandapuram", "Padalur"], 621104),
        format_district(618, "Pudukkottai", "RURAL", 80.5, "TIER_3", "Cashew Kernels & Virgin Coconut Oil / Granite", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Feeder", ["Pudukkottai", "Aranthangi", "Alangudi", "Gandarvakottai", "Viralimalai", "Thirumayam", "Ponnamaravathi", "Annavasal", "Arimalam", "Avudayarkoil", "Karambakudi", "Kunnandarkoil", "Manamelkudi", "Tiruvarankulam"], ["Kudumiyanmalai", "Narthamalai", "Kattumavadi", "Illupur"], 614616),
        format_district(619, "Ramanathapuram", "RURAL", 69.7, "TIER_3", "Gundu Dry Red Chilli (Mundu) & Marine Crab/Seaweed Culture", "AGRO_FISHERIES", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Coastal Feeder", ["Ramanathapuram", "Rameswaram", "Paramakudi", "Mudukulathur", "Kamuthi", "Kadaladi", "Thiruvadanai", "Mandapam", "Nainarkoil", "Bogalur", "RS Mangalam"], ["Sayalgudi", "Devipattinam", "Pamban", "Mandapam Camp"], 623707),
        format_district(729, "Ranipet", "SEMI_URBAN", 52.3, "TIER_3", "Finished Leather Footwear & Heavy Boiler Auxiliaries", "LEATHER_ENGINEERING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Industrial Feeder", ["Ranipet", "Arcot", "Walajah", "Sholinghur", "Arakkonam", "Nemili", "Timiri", "Kaveripakkam"], ["Mukundarayapuram", "Tajpura", "Banavaram", "Kalavai"], 632513),
        format_district(620, "Salem", "SEMI_URBAN", 48.4, "TIER_2", "Tapioca Sago (Sabudana) Processing & Handloom Silk / Steel", "AGRO_MINERAL", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Sago Agro Feeder", ["Salem", "Attur", "Mettur", "Omalur", "Edappadi", "Sankari", "Yercaud", "Valapady", "Ayothiyapattinam", "Gangavalli", "Kadayampatti", "Kolathur", "Mecheri", "Nangavalli", "Panamarathupatti", "Pethanaickenpalayam", "Thalaivasal", "Tharamangalam", "Veerapandi"], ["Mallur", "Attur Rural", "Jalagangapuram", "Sitheri"], 636102),
        format_district(621, "Sivaganga", "RURAL", 69.2, "TIER_3", "Chettinad Terracotta Pottery & Athangudi Handmade Cement Tiles", "HANDICRAFTS", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Feeder", ["Sivaganga", "Karaikudi", "Devakottai", "Manamadurai", "Ilayangudi", "Kalayarkoil", "Singampunari", "Sakkottai", "Kannankudi", "Kallal", "Thiruppuvanam", "Tirupathur"], ["Athangudi", "Manamadurai Rural", "Pillayarpatti", "Kandanur"], 630101),
        format_district(730, "Tenkasi", "RURAL", 58.1, "TIER_3", "Lemon Value Addition & Pattamadai Pai / Sengottai Spices", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Agro Feeder", ["Tenkasi", "Sankarankovil", "Kadayanallur", "Shenkottai", "Alangulam", "Kuruvikulam", "Keelapavoor", "Melaneelithanallur", "Vasudevanallur"], ["Puliyangudi", "Courtrallam Rural", "Surandai", "Sambavar Vadakarai"], 627855),
        format_district(622, "Thanjavur", "RURAL", 64.6, "TIER_3", "Thanjavur Art Plates, Bronze Sculptures & Paddy Processing", "HANDICRAFTS_AGRO", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Delta Agro Feeder", ["Thanjavur", "Kumbakonam", "Papanasam", "Pattukkottai", "Orathanadu", "Peravurani", "Thiruvaiyaru", "Ammapettai", "Budalur", "Madukkur", "Sethubhavachatram", "Thirupanandal", "Thiruvonam"], ["Swamimalai", "Nachiyarkoil", "Adirampattinam", "Melattur"], 612302),
        format_district(623, "Theni", "RURAL", 46.2, "TIER_3", "G-9 Cavendish Banana Processing & Cardamom Sorting", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Cardamom & Fruit Feeder", ["Theni", "Periyakulam", "Bodinayakanur", "Uthamapalayam", "Andipatti", "Chinnamanur", "Cumbum", "Kadamalaikundu-Myladumparai"], ["Cumbum Valley Rural", "Devadanapatti", "Kuchanur", "Kombai"], 625513),
        format_district(624, "Thoothukudi", "SEMI_URBAN", 49.9, "TIER_2", "Marine Seafood Cold Chain, Solar Salt Processing & Macaroons", "FISHERIES_FOOD", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Port & Salt Feeder", ["Thoothukudi", "Kovilpatti", "Tiruchendur", "Sathankulam", "Srivaikuntam", "Ottapidaram", "Vilathikulam", "Alwarthirunagari", "Karunkulam", "Kayathar", "Pudur", "Udangudi"], ["Kayalpattinam", "Authoor", "Eral", "Kurumbur"], 628501),
        format_district(625, "Tiruchirappalli", "SEMI_URBAN", 50.8, "TIER_2", "Grand Naine Banana Processing, Artificial Gems & Heavy Fabrication", "AGRO_FABRICATION", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Trichy Agro Feeder", ["Trichy", "Srirangam", "Lalgudi", "Manachanallur", "Musiri", "Thuraiyur", "Thottiyam", "Manapparai", "Andanallur", "Manikandam", "Marungapuri", "Pullambadi", "Tattayyangarpettai", "Uppiliyapuram", "Vaiyampatti"], ["Samayapuram", "Jeeyapuram", "Gunaseelam", "Navalpattu"], 621005),
        format_district(626, "Tirunelveli", "SEMI_URBAN", 50.1, "TIER_2", "Tirunelveli Wheat Halwa Confectionery & Banana Fiber Extraction", "FOOD_FIBER", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Wind Feeder", ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Cheranmahadevi", "Nanguneri", "Radhapuram", "Valliyoor", "Kalakadu", "Manur"], ["Pattamadai", "Kallidaikurichi", "Mukkudal", "Panagudi"], 627453),
        format_district(731, "Tirupathur", "RURAL", 64.9, "TIER_3", "Vaniyambadi/Ambur Finished Leather Goods & Natrampalli Jaggery", "LEATHER_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Industrial Feeder", ["Tirupathur", "Vaniyambadi", "Ambur", "Natrampalli", "Jolarpet", "Madhanur", "Alangayam", "Kandili"], ["Jolarpettai Rural", "Uthangarai Border", "Pudurnadu", "Yelagiri Hills"], 635802),
        format_district(627, "Tiruppur", "SEMI_URBAN", 38.6, "TIER_1", "Cotton Knitwear, Organic Garments & Kangeyam Coconut Oil", "TEXTILES_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Knitwear Line", ["Tiruppur", "Avinashi", "Palladam", "Kangeyam", "Dharapuram", "Udumalaipettai", "Madathukulam", "Kundadam", "Mulanur", "Pongalur", "Uthukuli", "Gudimangalam"], ["Uthukuli Butter Hub", "Kangeyam Rural", "Kunnathur", "Samalapuram"], 638701),
        format_district(628, "Tiruvallur", "SEMI_URBAN", 35.1, "TIER_2", "Heavy Commercial Vehicles, Engineering Auxiliaries & Dairy", "ENGINEERING_DAIRY", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Industrial Feeder", ["Tiruvallur", "Poonamallee", "Avadi", "Ponneri", "Gummidipoondi", "Uthukottai", "Tiruttani", "Ellapuram", "Kadambathur", "Minjur", "Poondi", "RK Pet", "Sholavaram", "Thiruvalangadu", "Villivakkam"], ["Periyapalayam", "Kavarapettai", "Thirumazhisai", "Naravarikuppam"], 601201),
        format_district(629, "Tiruvannamalai", "RURAL", 79.9, "TIER_3", "Aarni Silk Sarees, Ponni Rice Milling & Cheyyar Automotive", "SILK_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Weaver Feeder", ["Tiruvannamalai", "Arani", "Cheyyar", "Polur", "Chengam", "Vandavasi", "Kilpennathur", "Anakkavoor", "Chetpet", "Jawadhu Hills", "Kalasapakkam", "Peranamallur", "Pudupalayam", "Thandarampattu", "Thellar", "Vembakkam", "West Arani"], ["Devikapuram", "Vettavalam", "Kannanur", "Nammiyampattu"], 632301),
        format_district(630, "Tiruvarur", "RURAL", 79.6, "TIER_4", "Parboiled Rice Milling, Black Gram & Fish Farming", "AGRO_PROCESSING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Delta Agro Feeder", ["Tiruvarur", "Mannargudi", "Thiruthuraipoondi", "Needamangalam", "Nannilam", "Valangaiman", "Koradacheri", "Kottur", "Kudavasal", "Muthupet"], ["Vaduvur", "Thirumakkottai", "Peralam", "Alathambadi"], 614001),
        format_district(631, "Vellore", "SEMI_URBAN", 56.8, "TIER_2", "Vellore Spiny Brinjal Value Addition & Finished Leather Footwear", "AGRO_LEATHER", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Vellore Feeder", ["Vellore", "Katpadi", "Gudiyatham", "Anaicut", "Kaniyambadi", "Pernambut", "K.V. Kuppam"], ["Bagayam", "Senur", "Paradarami", "Pennathur"], 632059),
        format_district(632, "Viluppuram", "RURAL", 85.0, "TIER_3", "Groundnut Oil Processing & Cashew Processing / Terracotta", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Oil Mills Feeder", ["Viluppuram", "Tindivanam", "Gingee", "Vanur", "Marakkanam", "Vikaravandi", "Kandamangalam", "Kanai", "Koliyanur", "Mailam", "Melmalayanur", "Olakkur", "Thiruvennainallur", "Vallam"], ["Auroville Rural Fringe", "Gingee Fort Gaon", "Brammadesam", "Ananthapuram"], 604001),
        format_district(633, "Virudhunagar", "RURAL", 49.5, "TIER_3", "Sivakasi Printing & Packaging, Safety Matches & Sattur Sev", "PRINTING_FOOD", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Printing Feeder", ["Virudhunagar", "Sivakasi", "Sattur", "Rajapalayam", "Aruppukkottai", "Srivilliputhur", "Watrap", "Kariapatti", "Narikudi", "Tiruchuli", "Vembakottai"], ["Srivilliputhur Palkova Hub", "Alangulam Rural", "Pandalgudi", "Mamsapuram"], 626125)
    ]
    states.append({"stateCode": "33", "stateName": "Tamil Nadu", "territoryType": "STATE", "totalDistricts": 38, "districts": tn_districts})

    # 2. ANDHRA PRADESH (26)
    ap_names = [
        ("733", "Alluri Sitharama Raju", "RURAL", 89.0, "TIER_5", "Araku Valley Organic Arabica Coffee (G.I.) & Black Pepper", "AGRO_PLANTATION", ["Paderu", "Araku Valley", "Chintapalle", "Rampachodavaram", "Maredumilli", "G.K. Veedhi"], 531077),
        ("734", "Anakapalli", "SEMI_URBAN", 72.0, "TIER_3", "Anakapalle Sugarcane Jaggery & Metallurgical Fabrication", "AGRO_ENGINEERING", ["Anakapalli", "Chodavaram", "Madugula", "Narsipatnam", "Elamanchili", "Payakaraopeta"], 531001),
        ("502", "Ananthapuramu", "RURAL", 71.9, "TIER_3", "Groundnut Oil Expelling, Sweet Orange (Batayi) & Silk", "AGRO_SERICULTURE", ["Anantapur", "Guntakal", "Tadipatri", "Uravakonda", "Singanamala", "Kalyandurg", "Rayadurg"], 515001),
        ("735", "Annamayya", "RURAL", 78.0, "TIER_4", "Rayachoti Guava & Tomato Value Addition / Papaya", "HORTICULTURE", ["Rayachoti", "Madanapalle", "Rajampet", "Railway Kodur", "Thamballapalle", "Pileru"], 516269),
        ("736", "Bapatla", "RURAL", 77.0, "TIER_3", "Suryalanka Marine Fishery, Cashew & Bapatla Rice", "FISHERIES_AGRO", ["Bapatla", "Chirala", "Repalle", "Addanki", "Parchur", "Vemuru"], 522101),
        ("503", "Chittoor", "RURAL", 70.5, "TIER_2", "Totapuri Mango Pulping & Desi Dairy Ghee / Silk Reeling", "AGRO_DAIRY", ["Chittoor", "Palamaner", "Punganur", "Nagari", "GD Nellore", "Kuppam"], 517001),
        ("737", "Dr. B.R. Ambedkar Konaseema", "RURAL", 88.0, "TIER_3", "Coconut Coir Fiber, Coconut Oil & Freshwater Aquaculture Prawns", "COCONUT_FISHERIES", ["Amalapuram", "Razole", "Kothapeta", "Mandapeta", "Mummidivaram", "P.Gannavaram"], 533201),
        ("505", "East Godavari", "SEMI_URBAN", 68.0, "TIER_2", "Rajahmundry Paper Pulp, Tile Works & Floriculture of Kadiam", "WOOD_FLORICULTURE", ["Rajahmundry Urban", "Rajahmundry Rural", "Kovvur", "Nidadavole", "Gopalapuram", "Anaparthi"], 533101),
        ("738", "Eluru", "RURAL", 78.0, "TIER_3", "Eluru Handwoven Pile Carpets (G.I.) & Cocoa / Palm Oil", "CARPETS_AGRO", ["Eluru", "Chintalapudi", "Nuzvid", "Polavaram", "Denduluru", "Unguturu", "Musunuru"], 534001),
        ("506", "Guntur", "METROPOLITAN", 45.0, "TIER_1", "Guntur Sannam Red Chilli (G.I.), Cotton Spinning & Tobacco", "SPICES_TEXTILE", ["Guntur Urban", "Guntur Rural", "Tenali", "Mangalagiri", "Tadikonda", "Prathipadu"], 522002),
        ("739", "Kakinada", "SEMI_URBAN", 58.0, "TIER_2", "Deepwater Port Seafood Marine Processing & Kakinada Kaja Sweet", "FISHERIES_FOOD", ["Kakinada Urban", "Kakinada Rural", "Samalkot", "Peddapuram", "Pithapuram", "Tuni", "Prathipadu"], 533001),
        ("510", "Krishna", "SEMI_URBAN", 65.0, "TIER_2", "Machilipatnam Kalamkari Handblock Prints (G.I.) & Gold Covering", "HANDICRAFTS", ["Machilipatnam", "Gudivada", "Pedana", "Avanigadda", "Pamarru", "Penamaluru", "Gannavaram"], 521001),
        ("511", "Kurnool", "SEMI_URBAN", 71.0, "TIER_2", "Sona Masoori Rice Milling & Cotton Ginning / Cement", "AGRO_MINERAL", ["Kurnool", "Adoni", "Yemmiganur", "Kodumur", "Pattikonda", "Mantralayam", "Alur"], 518001),
        ("740", "Nandyal", "RURAL", 74.0, "TIER_3", "Nandyal Citrus & Bengal Gram (Chana) Milling / Stone Slabs", "AGRO_MINERAL", ["Nandyal", "Allagadda", "Banaganapalle", "Dhone", "Nandikotkur", "Srisailam", "Atmakur"], 518501),
        ("741", "NTR", "METROPOLITAN", 35.0, "TIER_1", "Automotive Spare Parts, Agro Warehousing & Kondapalli Wooden Toys (G.I.)", "ENGINEERING_TOYS", ["Vijayawada Urban", "Vijayawada Rural", "Mylavaram", "Tiruvuru", "Jaggayyapeta", "Nandigama", "Kanchikacherla"], 520001),
        ("742", "Palnadu", "RURAL", 79.0, "TIER_3", "Dry Chilli Oleoresin & Kotappakonda Traditional Brass Metal", "SPICES_BRASSWARE", ["Narasaraopet", "Sattenapalle", "Vinukonda", "Gurazala", "Macherla", "Chilakaluripet", "Pedakurapadu"], 522601),
        ("743", "Parvathipuram Manyam", "RURAL", 92.0, "TIER_5", "Cashew Processing & Organic Turmeric / Millets", "AGRO_PROCESSING", ["Parvathipuram", "Salur", "Palakonda", "Kurupam", "Gummalaxmipuram", "Komarada"], 535501),
        ("517", "Prakasam", "RURAL", 80.5, "TIER_3", "Markapur Slate Stone Products & Chimakurthi Galaxy Granite", "MINERAL_PROCESSING", ["Ongole", "Markapur", "Giddalur", "Kanigiri", "Kandukur", "Darsi", "Podili", "Yerragondapalem"], 523001),
        ("515", "Sri Potti Sriramulu Nellore", "SEMI_URBAN", 71.0, "TIER_2", "Aquaculture Marine Shrimp Freezing & Venkatagiri Silk Sarees (G.I.)", "FISHERIES_SILK", ["Nellore Urban", "Nellore Rural", "Kavali", "Gudur", "Atmakur", "Kovur", "Sarvepalli", "Udayagiri"], 524001),
        ("744", "Sri Sathya Sai", "RURAL", 79.0, "TIER_4", "Dharmavaram Handloom Silk Sarees (G.I.) & Groundnut", "HANDLOOM_AGRO", ["Puttaparthi", "Dharmavaram", "Kadiri", "Penukonda", "Hindupur", "Madakasira", "Gorantla"], 515134),
        ("519", "Srikakulam", "RURAL", 83.8, "TIER_3", "Ponduru Fine Khadi Cotton Handloom & Cashew Nut Kernel", "HANDLOOM_AGRO", ["Srikakulam", "Amadalavalasa", "Palasa-Kasibugga", "Narasannapeta", "Tekkali", "Ichchapuram", "Etcherla"], 532001),
        ("527", "Tirupati", "SEMI_URBAN", 58.0, "TIER_2", "Electronic Hardware Manufacturing & Wood Carvings / Tourism", "ELECTRONICS_HANDICRAFTS", ["Tirupati Urban", "Tirupati Rural", "Srikalahasti", "Chandragiri", "Sullurpeta (Space)", "Venkatagiri"], 517501),
        ("520", "Visakhapatnam", "METROPOLITAN", 12.0, "TIER_1", "Heavy Marine Shipbuilding, Steel, Petrochemicals & IT SEZ", "ENGINEERING_CHEMICALS", ["Visakhapatnam Urban", "Gajuwaka", "Bheemunipatnam", "Anandapuram", "Pendurthi"], 530001),
        ("521", "Vizianagaram", "RURAL", 79.1, "TIER_3", "Bobbili Veena Musical Instruments (G.I.) & Jute Twine Mills", "HANDICRAFTS_JUTE", ["Vizianagaram", "Bobbili", "Cheepurupalli", "Gajapathinagaram", "Nellimarla", "Srungavarapukota"], 535002),
        ("523", "West Godavari", "RURAL", 74.0, "TIER_2", "Narsapur Handmade Crochet Lace (G.I.) & Paddy Parboiling", "HANDICRAFTS_AGRO", ["Bhimavaram", "Tadepalligudem", "Tanuku", "Narsapur", "Palakollu", "Achanta", "Undi"], 534201),
        ("504", "YSR Kadapa", "SEMI_URBAN", 66.0, "TIER_2", "Kadapa Black Limestone Slabs & Banana / Turmeric Processing", "MINERAL_AGRO", ["Kadapa", "Proddatur", "Pulivendula", "Jammalamadugu", "Badvel", "Mydukur", "Kamalapuram"], 516001)
    ]
    ap_districts = [format_district(code, name, urb, rur, tier, odop, cat, "East Coast Plains and Hills Region (Zone XI)", "APSPDCL / APEPDCL Rural Feeder", blks, [f"{name} Rural", f"{blks[0]} GP"], pin) for code, name, urb, rur, tier, odop, cat, blks, pin in ap_names]
    states.append({"stateCode": "28", "stateName": "Andhra Pradesh", "territoryType": "STATE", "totalDistricts": 26, "districts": ap_districts})

    # 3. TELANGANA (33)
    tg_names = [
        ("680", "Adilabad", "RURAL", 76.3, "TIER_4", "Organic Cotton Ginning & Soyabean Oil Extraction", "AGRO_PROCESSING", ["Adilabad", "Boath", "Utnoor", "Bazarhathnoor", "Gudihatnoor"], 504001),
        ("681", "Bhadradri Kothagudem", "RURAL", 68.3, "TIER_4", "Kothagudem Mining Equipment, Coal Derivatives & Bamboo", "MINERAL_FOREST", ["Kothagudem", "Bhadrachalam", "Manuguru", "Yellandu", "Aswapuram"], 507101),
        ("682", "Hanamkonda", "SEMI_URBAN", 33.1, "TIER_2", "Warangal Cotton Dhurries & Handloom Weaving", "TEXTILES", ["Hanamkonda", "Kazipet", "Inavolu", "Hasanparthy", "Kamalapur"], 506001),
        ("518", "Hyderabad", "METROPOLITAN", 0.0, "TIER_1", "Biotech Vaccines, IT Software & Hyderabad Pearls/Zari", "BIOTECH_IT", ["Charminar", "Secunderabad", "Khairatabad", "Golconda", "Serilingampally"], 500001),
        ("683", "Jagtial", "RURAL", 77.6, "TIER_4", "Mango Pulp Extraction & Turmeric Processing", "AGRO_PROCESSING", ["Jagtial", "Korutla", "Metpally", "Dharmapuri", "Raikal"], 505327),
        ("684", "Jangaon", "RURAL", 87.4, "TIER_4", "Pembarthi Brass Metal Handicrafts & Cotton Baling", "HANDICRAFTS", ["Jangaon", "Bachannapet", "Devaruppula", "Palakurthi", "Station Ghanpur"], 506167),
        ("685", "Jayashankar Bhupalpally", "RURAL", 92.4, "TIER_5", "Tassar Silk Cocoon Rearing & Forest Honey", "SERICULTURE", ["Bhupalpally", "Kataram", "Mahadevpur", "Malhar Rao", "Mogullapalle"], 506169),
        ("686", "Jogulamba Gadwal", "RURAL", 89.6, "TIER_4", "Gadwal Zari Silk Sarees & Groundnut Seed Production", "HANDLOOM_AGRO", ["Gadwal", "Alampur", "Ieeja", "Itikyal", "Maldakal"], 509125),
        ("687", "Kamareddy", "RURAL", 87.3, "TIER_4", "Sugarcane Jaggery & Banswada Rice Processing", "AGRO_PROCESSING", ["Kamareddy", "Banswada", "Yellareddy", "Jukkal", "Bhiknoor"], 503111),
        ("520", "Karimnagar", "SEMI_URBAN", 69.3, "TIER_3", "Silver Filigree Handicrafts & Granite Cutting", "HANDICRAFTS_MINERAL", ["Karimnagar", "Huzurabad", "Choppadandi", "Manakondur", "Gangadhara"], 505001),
        ("521", "Khammam", "SEMI_URBAN", 77.4, "TIER_3", "Chilli Powder Processing & Granite Polishing", "AGRO_MINERAL", ["Khammam", "Madhira", "Wyra", "Sathupalli", "Kallur"], 507001),
        ("688", "Kumuram Bheem Asifabad", "RURAL", 83.1, "TIER_5", "Raw Cotton & Gum Karaya Forest Produce", "AGRO_FOREST", ["Asifabad", "Kagaznagar", "Sirpur", "Rebbena", "Jainoor"], 504293),
        ("689", "Mahabubabad", "RURAL", 90.1, "TIER_5", "Bayyaram Red Chilli & Turmeric Value Addition", "AGRO_PROCESSING", ["Mahabubabad", "Dornakal", "Kuravi", "Maripeda", "Nellikudur"], 506101),
        ("522", "Mahabubnagar", "RURAL", 79.4, "TIER_3", "Palamoor Woolen Blankets (Gongadi) & Maize Feed", "HANDLOOM_AGRO", ["Mahabubnagar", "Jadcherla", "Bhoothpur", "Devarkadra", "Nawabpet"], 509001),
        ("690", "Mancherial", "SEMI_URBAN", 56.1, "TIER_3", "Coal Mining Fabrication & Rice Bran Extraction", "ENGINEERING_AGRO", ["Mancherial", "Bellampalli", "Mandamarri", "Chennur", "Luxettipet"], 504208),
        ("523", "Medak", "RURAL", 92.3, "TIER_4", "Handloom Cotton Textiles & Maize Value Addition", "HANDLOOM_AGRO", ["Medak", "Narsapur", "Chegunta", "Ramayampet", "Shankarampet"], 502110),
        ("691", "Medchal-Malkajgiri", "METROPOLITAN", 8.5, "TIER_1", "Pharmaceutical Formulation & Industrial Valves", "PHARMA", ["Medchal", "Ghatkesar", "Keesara", "Alwal", "Malkajgiri"], 501401),
        ("692", "Mulugu", "RURAL", 96.1, "TIER_5", "Ramappa Heritage Crafts & Forest Tendu Leaves/Honey", "FOREST_CRAFT", ["Mulugu", "Venkatapur", "Govindaraopet", "Tadvai", "Eturnagaram"], 506343),
        ("693", "Nagarkurnool", "RURAL", 88.8, "TIER_4", "Groundnut Processing & Achampet Organic Honey", "AGRO_FOREST", ["Nagarkurnool", "Achampet", "Kollapur", "Kalwakurthy", "Bijinapalle"], 509209),
        ("524", "Nalgonda", "RURAL", 77.2, "TIER_3", "Fine Paddy Parboiling & Sweet Orange (Mosambi)", "AGRO_PROCESSING", ["Nalgonda", "Miryalaguda", "Devarakonda", "Nakrekal", "Chityal"], 508001),
        ("694", "Narayanpet", "RURAL", 88.4, "TIER_5", "Narayanpet Handloom Silk & Cotton Sarees", "HANDLOOM", ["Narayanpet", "Makthal", "Kosgi", "Damaragidda", "Maddur"], 509210),
        ("695", "Nirmal", "RURAL", 78.6, "TIER_4", "Nirmal Wooden Toys, Paintings & Turmeric Processing", "HANDICRAFTS", ["Nirmal", "Bhainsa", "Khanapur", "Kaddammeddi", "Sarangapur"], 504106),
        ("525", "Nizamabad", "SEMI_URBAN", 70.4, "TIER_3", "Armoor Turmeric Processing & Seed Rice Cultivation", "AGRO_PROCESSING", ["Nizamabad", "Bodhan", "Armoor", "Bheemgal", "Dichpally"], 503001),
        ("696", "Peddapalli", "SEMI_URBAN", 61.8, "TIER_3", "Thermal Power Auxiliaries & Paddy Milling", "ENGINEERING_AGRO", ["Peddapalli", "Ramagundam", "Manthani", "Sultanabad", "Julapalle"], 505172),
        ("697", "Rajanna Sircilla", "RURAL", 78.8, "TIER_3", "Sircilla Powerloom Polyester & Cotton Textiles", "TEXTILES", ["Sircilla", "Vemulawada", "Yellareddypet", "Mustabad", "Gambhiraopet"], 505301),
        ("526", "Ranga Reddy", "METROPOLITAN", 42.3, "TIER_1", "Aerospace Hardware, Precision Casting & Vegetables", "AEROSPACE_AGRO", ["Rajendranagar", "Ibrahimpatnam", "Chevella", "Shadnagar", "Maheshwaram"], 501510),
        ("698", "Sangareddy", "SEMI_URBAN", 65.3, "TIER_2", "Pashamylaram Chemical Equipment & Zaheerabad Ginger", "CHEMICAL_AGRO", ["Sangareddy", "Zaheerabad", "Patancheru", "Narayankhed", "Andole"], 502001),
        ("699", "Siddipet", "RURAL", 86.3, "TIER_3", "Gollabhama Handloom Sarees & Dairy Processing", "HANDLOOM_DAIRY", ["Siddipet", "Gajwel", "Dubbak", "Husnabad", "Cherial"], 502103),
        ("700", "Suryapet", "RURAL", 84.5, "TIER_3", "Paddy Milling & Cement Concrete Products", "AGRO_MINERAL", ["Suryapet", "Kodad", "Huzurnagar", "Thungathurthy", "Mothey"], 508213),
        ("701", "Vikarabad", "RURAL", 86.5, "TIER_4", "Tandur Red Gram (Tur Dal) & Tandur Blue Limestone", "AGRO_MINERAL", ["Vikarabad", "Tandur", "Pargi", "Kodangal", "Dharur"], 501101),
        ("702", "Wanaparthy", "RURAL", 84.0, "TIER_4", "Wanaparthy Peanuts (Groundnut) Processing & Poultry", "AGRO_PROCESSING", ["Wanaparthy", "Pebbair", "Ghanpur", "Gopalpeta", "Kothakota"], 509381),
        ("528", "Warangal", "SEMI_URBAN", 72.0, "TIER_3", "Red Chilli Value Addition & Parboiled Rice Mills", "AGRO_PROCESSING", ["Warangal Rural", "Narsampet", "Wardhannapet", "Parkal", "Geesugonda"], 506002),
        ("703", "Yadadri Bhuvanagiri", "RURAL", 83.3, "TIER_3", "Pochampally Ikat Handloom Silk Sarees", "HANDLOOM", ["Bhongir", "Pochampally", "Choutuppal", "Alair", "Mothkur"], 508116)
    ]
    tg_districts = [format_district(code, name, urb, rur, tier, odop, cat, "Southern Plateau and Hills Region (Zone X)", "TSSPDCL / TSNPDCL Rural Feeder", blks, [f"{name} Rural", f"{blks[0]} GP"], pin) for code, name, urb, rur, tier, odop, cat, blks, pin in tg_names]
    states.append({"stateCode": "36", "stateName": "Telangana", "territoryType": "STATE", "totalDistricts": 33, "districts": tg_districts})

    # 3. KARNATAKA (31)
    ka_names = [
        ("555", "Bagalkote", "RURAL", 68.4, "TIER_3", "Ilkal Handloom Sarees & Guledgudda Khana Fabric", "HANDLOOM", ["Bagalkote", "Badami", "Ilkal", "Jamkhandi", "Mudhol", "Hunagund"], 587101),
        ("556", "Ballari", "SEMI_URBAN", 62.5, "TIER_2", "Readymade Denim Garments & Sponge Iron Fabrication", "TEXTILES_METAL", ["Ballari", "Sandur", "Siruguppa", "Kampli", "Kurugodu"], 583101),
        ("557", "Belagavi", "SEMI_URBAN", 74.7, "TIER_2", "Belagavi Kunda Milk Sweet & Sugar Distillery Byproducts", "AGRO_FOOD", ["Belagavi", "Gokak", "Chikkodi", "Athani", "Bailhongal", "Hukkeri", "Khanapur", "Ramdurg", "Raybag", "Saundatti"], 590001),
        ("558", "Bengaluru Rural", "SEMI_URBAN", 72.9, "TIER_2", "Mulberry Silk Cocoon Processing & Polyhouse Floriculture", "SERICULTURE_AGRO", ["Devanahalli", "Doddaballapura", "Hosakote", "Nelamangala"], 562110),
        ("559", "Bengaluru Urban", "METROPOLITAN", 9.1, "TIER_1", "Information Technology, Aerospace Electronics & Biotech", "IT_ELECTRONICS", ["Bengaluru North", "Bengaluru South", "Bengaluru East", "Anekal", "Yelahanka"], 560001),
        ("560", "Bidar", "RURAL", 75.0, "TIER_3", "Bidriware Silver Inlay Metal Craft & Ginger Processing", "HANDICRAFTS_AGRO", ["Bidar", "Basavakalyan", "Bhalki", "Humnabad", "Aurad"], 585401),
        ("561", "Chamarajanagara", "RURAL", 82.9, "TIER_4", "Silk Weaving & Turmeric / Banana Value Addition", "HANDLOOM_AGRO", ["Chamarajanagar", "Gundlupet", "Kollegal", "Yelandur", "Hanur"], 571313),
        ("562", "Chikkaballapura", "RURAL", 77.6, "TIER_3", "Polyhouse Rose Floriculture & Grape Processing (Wine)", "HORTICULTURE", ["Chikkaballapur", "Gauribidanur", "Bagepalli", "Sidlaghatta", "Chintamani"], 562101),
        ("563", "Chikkamagaluru", "RURAL", 79.0, "TIER_3", "Arabica & Robusta Single Estate Coffee Processing", "AGRO_PLANTATION", ["Chikkamagaluru", "Mudigere", "Koppa", "Sringeri", "Narasimharajapura", "Tarikere", "Kadur"], 577101),
        ("564", "Chitradurga", "RURAL", 80.1, "TIER_3", "Pomegranate (Bhagwa) & Groundnut Oil Expelling", "AGRO_PROCESSING", ["Chitradurga", "Hiriyur", "Challakere", "Holalkere", "Hosadurga", "Molakalmuru"], 577501),
        ("565", "Dakshina Kannada", "SEMI_URBAN", 52.3, "TIER_1", "Marine Fish Freezing & Mangalore Cashew Export Processing", "FISHERIES_AGRO", ["Mangaluru", "Bantwal", "Puttur", "Belthangady", "Sullia", "Moodabidri", "Kadaba"], 575001),
        ("566", "Davanagere", "SEMI_URBAN", 67.7, "TIER_2", "Davanagere Benne Dosa Ingredients & Maize Processing", "AGRO_PROCESSING", ["Davanagere", "Harihar", "Honnali", "Channagiri", "Jagalur", "Nyamathi"], 577001),
        ("567", "Dharwad", "SEMI_URBAN", 43.2, "TIER_2", "Dharwad Pedha Milk Confectionery & Navalgund Jamakhana", "FOOD_HANDICRAFTS", ["Dharwad", "Hubballi", "Navalgund", "Kundgol", "Kalghatgi", "Alnavar"], 580001),
        ("568", "Gadag", "RURAL", 64.4, "TIER_3", "Byadgi-type Dry Chilli Processing & Betageri Handlooms", "AGRO_HANDLOOM", ["Gadag", "Betageri", "Ron", "Shirhatti", "Nargund", "Mundargi", "Gajendragad"], 582101),
        ("569", "Hassan", "RURAL", 78.8, "TIER_3", "Coffee Curing, Cardamom Processing & Potato Cold Storage", "AGRO_PROCESSING", ["Hassan", "Arsikere", "Channarayapatna", "Holenarasipura", "Sakleshpur", "Arkalgud", "Belur", "Alur"], 573201),
        ("570", "Haveri", "RURAL", 79.2, "TIER_3", "Byadagi Dry Red Chilli Extraction & Spice Oleoresins", "AGRO_PROCESSING", ["Haveri", "Byadgi", "Ranebennur", "Hirekerur", "Hangal", "Savanur", "Shiggaon"], 581110),
        ("571", "Kalaburagi", "SEMI_URBAN", 67.4, "TIER_2", "Gulbarga Red Gram (Tur Dal G.I.) Dehusking Mills", "AGRO_PROCESSING", ["Kalaburagi", "Sedam", "Chittapur", "Afzalpur", "Aland", "Chincholi", "Jevargi"], 585101),
        ("572", "Kodagu", "RURAL", 85.4, "TIER_4", "Coorg Specialty Coffee, Black Pepper & Coorg Honey", "AGRO_PLANTATION", ["Madikeri", "Virajpet", "Somwarpet", "Ponnampet", "Kushalnagar"], 571201),
        ("573", "Kolar", "RURAL", 68.7, "TIER_3", "Commercial Tomato Value Addition & Mulberry Silk Reeling", "AGRO_SERICULTURE", ["Kolar", "Bangarapet", "Malur", "Mulbagal", "Srinivaspur"], 563101),
        ("574", "Koppal", "RURAL", 83.2, "TIER_4", "Kinhal Wooden Lacquer Toys & Guava Processing", "HANDICRAFTS_AGRO", ["Koppal", "Gangavathi", "Kushtagi", "Yelburga", "Kanakagiri", "Karatagi"], 583231),
        ("575", "Mandya", "RURAL", 82.9, "TIER_3", "Sugarcane Organic Jaggery & Maddur Vada Rice Flour", "AGRO_PROCESSING", ["Mandya", "Maddur", "Malavalli", "Pandavapura", "Srirangapatna", "Krishnarajpet", "Nagamangala"], 571401),
        ("576", "Mysuru", "SEMI_URBAN", 58.5, "TIER_1", "Mysore Pure Silk Sarees, Sandalwood Carving & Rosewood Inlay", "HANDLOOM_HANDICRAFTS", ["Mysuru", "Nanjangud", "T.Narasipura", "Hunsur", "Piriyapatna", "K.R.Nagar", "Saragur"], 570001),
        ("577", "Raichur", "RURAL", 74.5, "TIER_3", "Sona Masoori Rice Milling & Raw Cotton Ginning", "AGRO_PROCESSING", ["Raichur", "Manvi", "Sindhanur", "Devadurga", "Lingasugur", "Maski", "Sirwar"], 584101),
        ("578", "Ramanagara", "RURAL", 75.3, "TIER_3", "Asia's Largest Silk Cocoon Market & Channapatna Wooden Toys", "SERICULTURE_TOYS", ["Ramanagara", "Channapatna", "Kanakapura", "Magadi"], 562159),
        ("579", "Shivamogga", "SEMI_URBAN", 64.4, "TIER_2", "Arecanut Processing, Betel Nut Value Addition & Iron Works", "AGRO_ENGINEERING", ["Shivamogga", "Bhadravathi", "Sagar", "Shikaripura", "Soraba", "Thirthahalli", "Hosanagara"], 577201),
        ("580", "Tumakuru", "RURAL", 77.6, "TIER_2", "Desiccated Coconut Powder & Tamarind Processing", "AGRO_PROCESSING", ["Tumakuru", "Tiptur", "Sira", "Kunigal", "Gubbi", "Madhugiri", "Pavagada", "Chikkanayakanahalli", "Turuvekere", "Koratagere"], 572101),
        ("581", "Udupi", "SEMI_URBAN", 71.6, "TIER_2", "Mattu Gulla Eggplant Value Addition & Cashew Processing", "AGRO_PROCESSING", ["Udupi", "Kundapura", "Karkala", "Byndoor", "Brahmavara", "Kapu", "Hebri"], 576101),
        ("582", "Uttara Kannada", "RURAL", 70.9, "TIER_3", "Spices, Areca Nut & Honey Processing / Yellapur Forest Produce", "AGRO_FOREST", ["Karwar", "Sirsi", "Kumta", "Bhatkal", "Ankola", "Haliyal", "Honnavar", "Joida", "Mundgod", "Siddapur", "Yellapur"], 581301),
        ("732", "Vijayanagara", "RURAL", 72.0, "TIER_3", "Banana Fiber Extraction & Hampi Terracotta Crafts", "AGRO_HANDICRAFTS", ["Hosapete", "Hagaribommanahalli", "Harapanahalli", "Hoovina Hadagali", "Kotturu", "Kudligi"], 583201),
        ("583", "Vijayapura", "RURAL", 76.9, "TIER_3", "Grape Processing, Raisin Making & Lime Processing", "HORTICULTURE", ["Vijayapura", "Indi", "Basavana Bagewadi", "Sindagi", "Muddebihal", "Talikoti", "Chadchan", "Tikota"], 586101),
        ("584", "Yadgir", "RURAL", 81.2, "TIER_4", "Pigeon Pea (Red Gram) & Groundnut Processing", "AGRO_PROCESSING", ["Yadgir", "Shahapur", "Shorapur", "Hunsagi", "Gurmitkal", "Wadgera"], 585201)
    ]
    ka_districts = [format_district(code, name, urb, rur, tier, odop, cat, "Southern Plateau and Hills Region (Zone X)", "BESCOM / HESCOM / MESCOM Rural Feeder", blks, [f"{name} Rural", f"{blks[0]} GP"], pin) for code, name, urb, rur, tier, odop, cat, blks, pin in ka_names]
    states.append({"stateCode": "29", "stateName": "Karnataka", "territoryType": "STATE", "totalDistricts": 31, "districts": ka_districts})

    # 4. KERALA (14)
    kl_names = [
        ("585", "Alappuzha", "SEMI_URBAN", 46.2, "TIER_2", "Coir Mats, Geotextiles & Marine Clam Processing", "COIR_FISHERIES", ["Ambalappuzha", "Cherthala", "Kuttanad", "Karthikappally", "Chengannur", "Mavelikkara"], 688001),
        ("586", "Ernakulam", "METROPOLITAN", 32.0, "TIER_1", "Marine Fish Exports, Spice Oleoresins & Petrochemicals", "FISHERIES_SPICES", ["Kochi", "Kanayannur", "Aluva", "Kunnathunad", "Muvattupuzha", "Kothamangalam", "Paravur"], 682001),
        ("587", "Idukki", "RURAL", 95.3, "TIER_4", "Alleppey Green Cardamom, Tea & Hill Spices / Honey", "SPICES_PLANTATION", ["Thodupuzha", "Devikulam", "Udumbanchola", "Peerumade", "Idukki"], 685603),
        ("588", "Kannur", "SEMI_URBAN", 34.9, "TIER_2", "Kannur Handloom Fabrics & Export Plywood Manufacturing", "HANDLOOM_WOOD", ["Kannur", "Thalassery", "Taliparamba", "Payyannur", "Iritty"], 670001),
        ("589", "Kasaragod", "RURAL", 61.1, "TIER_3", "Bekal Cashew Processing & Kasaragod Handloom Sarees", "AGRO_HANDLOOM", ["Kasaragod", "Hosdurg", "Manjeshwaram", "Vellarikundu"], 671121),
        ("590", "Kollam", "SEMI_URBAN", 54.9, "TIER_2", "Kollam Cashew Nut Shelling & Marine Fisheries Export", "AGRO_FISHERIES", ["Kollam", "Karunagappally", "Kunnathur", "Kottarakkara", "Punalur", "Pathanapuram"], 691001),
        ("591", "Kottayam", "SEMI_URBAN", 71.4, "TIER_2", "Natural Rubber Latex Products & Cocoa Processing", "RUBBER_AGRO", ["Kottayam", "Changanassery", "Vaikom", "Meenachil", "Kanjirappally"], 686001),
        ("592", "Kozhikode", "SEMI_URBAN", 32.9, "TIER_1", "Calico Handlooms, Kozhikode Halwa & Virgin Coconut Oil", "FOOD_COCONUT", ["Kozhikode", "Vatakara", "Koyilandy", "Thamarassery"], 673001),
        ("593", "Malappuram", "SEMI_URBAN", 55.8, "TIER_2", "Coconut Byproducts, Banana Chips & Bamboo Furniture", "AGRO_FOOD", ["Eranad", "Tirur", "Perinthalmanna", "Nilambur", "Ponnani", "Kondotty", "Tirurangadi"], 676505),
        ("594", "Palakkad", "RURAL", 75.9, "TIER_3", "Palakkadan Matta Rice Milling & Coconut Oil Extraction", "AGRO_PROCESSING", ["Palakkad", "Alathur", "Chittur", "Ottappalam", "Mannarkkad", "Pattambi"], 678001),
        ("595", "Pathanamthitta", "RURAL", 89.0, "TIER_3", "Aranmula Metal Mirror (Kannadi) & Sugar/Honey Derivatives", "HANDICRAFTS_AGRO", ["Kozhencherry", "Adoor", "Ranni", "Mallappally", "Konni", "Thiruvalla"], 689645),
        ("596", "Thiruvananthapuram", "SEMI_URBAN", 46.3, "TIER_1", "Balaramapuram Cotton Handloom Sarees & Tapioca Value Addition", "HANDLOOM_AGRO", ["Thiruvananthapuram", "Neyyattinkara", "Nedumangad", "Chirayinkeezhu", "Varkala", "Kattakada"], 695001),
        ("597", "Thrissur", "SEMI_URBAN", 32.8, "TIER_2", "Gold Jewellery Manufacturing & Ayurveda Medicines", "JEWELLERY_AYURVEDA", ["Thrissur", "Mukundapuram", "Chalakudy", "Kodungallur", "Chavakkad", "Thalapilly", "Kunnamkulam"], 680001),
        ("598", "Wayanad", "RURAL", 96.1, "TIER_4", "Wayanad Robusta Coffee, Wayanad Pepper & Organic Ginger", "PLANTATION_SPICES", ["Vythiri", "Sulthan Bathery", "Mananthavady"], 673121)
    ]
    kl_districts = [format_district(code, name, urb, rur, tier, odop, cat, "West Coast Plains and Ghats Region (Zone XII)", "KSEB Rural Agro Feeder", blks, [f"{name} Rural", f"{blks[0]} GP"], pin) for code, name, urb, rur, tier, odop, cat, blks, pin in kl_names]
    states.append({"stateCode": "32", "stateName": "Kerala", "territoryType": "STATE", "totalDistricts": 14, "districts": kl_districts})

    # 5. PUDUCHERRY (4)
    py_names = [
        ("634", "Karaikal", "SEMI_URBAN", 51.0, "TIER_3", "Marine Fisheries Value Addition & Salt Pan Refinement", "FISHERIES", ["Karaikal", "Nedungadu", "Kottucherry", "Neravy", "Thirunallar"], 609602),
        ("635", "Mahe", "URBAN", 0.0, "TIER_3", "Traditional Seafood Processing & Coconut Wood Craft", "FISHERIES_CRAFT", ["Mahe"], 673310),
        ("636", "Puducherry", "SEMI_URBAN", 31.7, "TIER_2", "Handmade Paper, Aroma Candles & Leather Goods", "HANDICRAFTS", ["Ariyankuppam", "Villianur", "Bahour"], 605001),
        ("637", "Yanam", "URBAN", 0.0, "TIER_3", "Estuarine Aquaculture & Coconut Oil Processing", "FISHERIES_AGRO", ["Yanam"], 533464)
    ]
    py_districts = [format_district(code, name, urb, rur, tier, odop, cat, "East Coast Plains and Hills Region (Zone XI)", "Electricity Department Puducherry Feeder", blks, [f"{name} Rural", f"{blks[0]} GP"], pin) for code, name, urb, rur, tier, odop, cat, blks, pin in py_names]
    states.append({"stateCode": "34", "stateName": "Puducherry", "territoryType": "UNION_TERRITORY", "totalDistricts": 4, "districts": py_districts})

    # 6. LAKSHADWEEP (1)
    lk_districts = [
        format_district(553, "Lakshadweep", "RURAL", 22.0, "TIER_5", "Masmin Dried Skipjack Tuna & Virgin Coconut Oil", "FISHERIES_COCONUT", "Island Region (Zone XV)", "Lakshadweep Electricity Dept Solar-Diesel Grid", ["Kavaratti", "Agatti", "Amini", "Andrott", "Kalpeni", "Minicoy", "Kadmat", "Kiltan", "Chetlat", "Bitra"], ["Kavaratti Dweep", "Agatti Island GP", "Minicoy Island GP"], 682555)
    ]
    states.append({"stateCode": "31", "stateName": "Lakshadweep", "territoryType": "UNION_TERRITORY", "totalDistricts": 1, "districts": lk_districts})

    # 7. ANDAMAN AND NICOBAR ISLANDS (3)
    an_names = [
        ("600", "Nicobars", "RURAL", 100.0, "TIER_6", "Virgin Coconut Oil & Spices / Organic Marine Tuna", "COCONUT_FISHERIES", ["Car Nicobar", "Nancowry", "Great Nicobar"], 744301),
        ("601", "North and Middle Andaman", "RURAL", 91.0, "TIER_5", "Organic Betel Nut, Black Pepper & Coconut Processing", "AGRO_PROCESSING", ["Diglipur", "Mayabunder", "Rangat"], 744202),
        ("599", "South Andaman", "SEMI_URBAN", 44.0, "TIER_3", "Marine Seafood Freezing & Shell/Wood Handicrafts", "FISHERIES_CRAFT", ["Port Blair", "Ferrargunj", "Little Andaman"], 744101)
    ]
    an_districts = [format_district(code, name, urb, rur, tier, odop, cat, "Island Region (Zone XV)", "Electricity Dept Andaman Feeder", blks, [f"{name} Rural", f"{blks[0]} GP"], pin) for code, name, urb, rur, tier, odop, cat, blks, pin in an_names]
    states.append({"stateCode": "35", "stateName": "Andaman and Nicobar Islands", "territoryType": "UNION_TERRITORY", "totalDistricts": 3, "districts": an_districts})

    return states
