#!/usr/bin/env python3
"""
Master data builder for all 28 States and 8 Union Territories in India (788+ Districts).
Outputs fully typed TypeScript data for src/data/lgdLocations.ts
and python reference store for backend/app/domains/geography/data_store.py
"""

import os
import json

def get_state_districts_data():
    # Return dictionary mapping each state/UT to its full district records
    # Format: (districtCode, districtName, urbanityClassification, censusRuralPercentage, rbiTier, notifiedODOP, odopCategory, agroClimaticZone, powerTariffZone, blocks, sampleGPs, sampleVillage, pincode, habitations)
    return {
        ("33", "Tamil Nadu", "STATE", 38): [
            ("602", "Ariyalur", "RURAL", 89.0, "TIER_4", "Cashew Processing & Roasted Kernels / Lime", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Distribution Feeder", ["Ariyalur", "Sendurai", "Udayarpalayam", "Andimadam", "Jayankondam", "T.Palur"], ["Valajanagaram", "Subbrayapuram", "Kallankurichi", "Thirumanur"], "Valajanagaram Gaon", "621704", ["Kottai Medu", "Kudikadu", "Koil Vattam"]),
            ("726", "Chengalpattu", "SEMI_URBAN", 40.5, "TIER_2", "Automotive Engineering Components & Marine Fisheries", "ENGINEERING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Industrial & Peri-Urban Feeder", ["Chengalpattu", "Kattankulathur", "Maduranthakam", "St. Thomas Mount", "Tiruporur", "Lathur", "Chithamur"], ["Acharapakkam", "Nemmeli", "Kelambakkam", "Kovalam", "Vandalur"], "Nemmeli Coastal Gaon", "603104", ["Fisherman Colony", "Kuppam Medu", "East Coast Vasti"]),
            ("603", "Chennai", "METROPOLITAN", 0.0, "TIER_1", "Leather Goods, Footwear & IT / SaaS Solutions", "LEATHER_IT", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Metro Priority Grid (24x7)", ["Egmore", "Guindy", "Mylapore", "Tondiarpet", "Velachery", "Ambattur", "Alandur"], ["Chennai Corporation Zone 1", "Chennai Corporation Zone 5", "Chennai Corporation Zone 10"], "Guindy Industrial Ward", "600032", ["Estate Main Road", "Labour Colony", "Tech Park Zone"]),
            ("604", "Coimbatore", "SEMI_URBAN", 24.2, "TIER_1", "Pump Motors, Foundry Castings & Organic Coconut Coir", "ENGINEERING_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Coimbatore High Tension / Agro Feeder", ["Pollachi North", "Pollachi South", "Sulur", "Annur", "Karamadai", "Madukkarai", "Perur", "Thondamuthur"], ["Samathur", "Kinathukadavu", "Negamam", "Zamin Uthukuli"], "Samathur Gaon", "642123", ["Coir Mill Colony", "Thottam Vasti", "Kisan Nagar"]),
            ("605", "Cuddalore", "RURAL", 66.0, "TIER_3", "Cashew Nut Processing & Jackfruit Pulping", "AGRO_PROCESSING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Cuddalore Rural Feeder", ["Cuddalore", "Panruti", "Kurinjipadi", "Bhuvanagiri", "Kattumannarkoil", "Vridhachalam", "Kammapuram"], ["Semakottai", "Marungur", "Melpattampakkam", "Thiruvathigai"], "Panruti Rural", "607106", ["Cashew Thoppu", "Kudikadu", "Mettu Theru"]),
            ("606", "Dharmapuri", "RURAL", 83.1, "TIER_4", "Mango Pulp Extraction & Finger Millet (Ragi) Value Addition", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Dharmapuri Agro Feeder", ["Dharmapuri", "Pennagaram", "Harur", "Palacode", "Karimangalam", "Morappur", "Pappireddipatti"], ["Kaveripattinam", "Indur", "Nallampalli", "Eriyur"], "Palacode Mango Village", "636808", ["Thoppur Vasti", "Kollai Medu", "Ragi Kalainagar"]),
            ("607", "Dindigul", "RURAL", 62.6, "TIER_3", "Dindigul Brass Locks & Nilakottai Cut Flowers / Gloriosa", "HANDICRAFTS_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Dindigul Rural Feeder", ["Dindigul", "Nilakottai", "Oddanchatram", "Palani", "Kodaikanal", "Athoor", "Batlagundu", "Natham", "Vedasandur"], ["Pallapatti", "Siluvathur", "Vembarpatti", "Ayyalur"], "Nilakottai Flower Hub", "624208", ["Malli Garden", "Lock Artisan Colony", "Kottai Street"]),
            ("608", "Erode", "SEMI_URBAN", 48.6, "TIER_2", "Turmeric Processing & Powerloom Bedspread Handlooms", "AGRO_TEXTILES", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Erode Industrial/Rural Feeder", ["Erode", "Bhavani", "Gobichettipalayam", "Perundurai", "Sathyamangalam", "Anthiyur", "Modakkurichi", "Kodumudi"], ["Kalingarayanpalayam", "Gobi Rural", "Nambiyur", "Kavindapadi"], "Gobichettipalayam Agro Hub", "638452", ["Turmeric Mandi Compound", "Kudi Theru", "Weaver Nagar"]),
            ("727", "Kallakurichi", "RURAL", 85.4, "TIER_4", "Sugarcane Jaggery & Rice Processing / Tapioca Sago", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Feeder", ["Kallakurichi", "Chinnasalem", "Sankarapuram", "Rishivandiyam", "Thirukovilur", "Ulundurpet"], ["Kachirayapalayam", "Pakkaimedu", "Pottiyam", "Kariyalur"], "Chinnasalem Jaggery Gaon", "606201", ["Karumbu Thottam", "Aadivasi Hamlet", "Kollai Basti"]),
            ("609", "Kanchipuram", "SEMI_URBAN", 36.5, "TIER_2", "Kanchipuram Pure Mulberry Silk Sarees & Zari Weaving", "HANDLOOM_TEXTILE", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Kanchi Semi-Urban Feeder", ["Kanchipuram", "Walajabad", "Sriperumbudur", "Kundrathur", "Uthiramerur"], ["Orikkai", "Perunagar", "Manampathi", "Vada Illuppai"], "Orikkai Weaver Hamlet", "631502", ["Silk Weaver Street", "Zari Workshop Colony", "Kudikadu"]),
            ("610", "Kanyakumari", "SEMI_URBAN", 17.7, "TIER_2", "Natural Rubber Products & Cloves / Fish Processing", "AGRO_PROCESSING", "West Coast Plains and Ghats Region (Zone XII)", "TANGEDCO Coastal Grid Feeder", ["Agastheeswaram", "Rajakkamangalam", "Thovalai", "Kurunthancode", "Tuckalay", "Thiruvattar", "Killiyoor", "Munchirai", "Melpuram"], ["Suchindram", "Marthandam", "Colachel Rural", "Kadiapattanam"], "Marthandam Honey & Rubber Gaon", "629165", ["Rubber Plantation Hamlet", "Beekeeper Lane", "Coastal Settlement"]),
            ("611", "Karur", "SEMI_URBAN", 59.2, "TIER_3", "Home Textiles, Kitchen Linen & Mosquito Net Manufacture", "TEXTILES", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Karur Industrial Feeder", ["Karur", "Thanthoni", "Aravakurichi", "K.Paramathi", "Kulithalai", "Krishnarayapuram", "Kadavur"], ["Vengamedu", "Pallapatti", "Inungur", "Mayanur"], "Thanthoni Textile Village", "639005", ["Weaving Unit Colony", "Linen Mill Area", "Kisan Puram"]),
            ("612", "Krishnagiri", "RURAL", 77.2, "TIER_3", "Commercial Mango Pulp Concentrates & Granite Carvings", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Krishnagiri Agro Feeder", ["Krishnagiri", "Hosur", "Bargur", "Kaveripattinam", "Pochampalli", "Uthangarai", "Mathur", "Shoolagiri", "Kelamangalam"], ["Kandikuppam", "Pannandur", "Biligundlu", "Royakottai"], "Bargur Mango Pulp Gaon", "635108", ["Mango Orchard Colony", "Granite Quarry Basti", "Kudil"]),
            ("613", "Madurai", "SEMI_URBAN", 39.2, "TIER_1", "Madurai Malli (Jasmine Flower) Perfume Extracts & Handloom Sungudi Sarees", "AGRO_TEXTILE", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Madurai Central/Rural Feeder", ["Madurai East", "Madurai West", "Thiruparankundram", "Melur", "Vadipatti", "Alanganallur", "Usilampatti", "Tirumangalam"], ["Thirumogur", "Othakadai", "Alanganallur Rural", "Sholavandan"], "Alanganallur Jasmine Hub", "625501", ["Jasmine Farm Colony", "Sungudi Weaver Street", "Kisan Nagar"]),
            ("728", "Mayiladuthurai", "RURAL", 78.5, "TIER_3", "Seafood Cold Chain Processing & Poompuhar Bronze Icons", "FISHERIES_HANDICRAFTS", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Coastal Rural Feeder", ["Mayiladuthurai", "Kuthalam", "Sirkazhi", "Sembanarkoil", "Kollidam"], ["Poompuhar", "Tharangambadi", "Vaitheeswarankoil", "Manalmedu"], "Poompuhar Coastal Gaon", "609105", ["Bronze Artisan Basti", "Fishermen Sea Colony", "Mettu Theru"]),
            ("614", "Nagapattinam", "RURAL", 77.4, "TIER_3", "Marine Fish & Shrimp Processing / Salt Extraction", "FISHERIES", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Coastal Feeder", ["Nagapattinam", "Keelaiyur", "Kilvelur", "Thirumarugal", "Vedaranyam", "Thalainayar"], ["Velankanni Rural", "Vedaranyam Salt Flats", "Kodiyakarai", "Sikkal"], "Vedaranyam Salt Village", "614810", ["Salt Pan Workers Colony", "Kuppam Vasti", "Kisan Nagar"]),
            ("615", "Namakkal", "RURAL", 59.7, "TIER_3", "Poultry Layer Egg Products, Feed Mills & Rig Body Building", "POULTRY_ENGINEERING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Poultry Agro Feeder", ["Namakkal", "Rasipuram", "Tiruchengode", "Paramathi", "Kolli Hills", "Sendamangalam", "Mohanur"], ["Valavanthi Nadu", "Seerapalli", "Thindamangalam", "Nallipalayam"], "Tiruchengode Poultry Hub", "637211", ["Poultry Farm Cluster", "Lorry Body Works Lane", "Egg Packaging Yard"]),
            ("616", "Nilgiris", "RURAL", 60.8, "TIER_3", "Orthodox Nilgiri Hill Tea & Eucalyptus Essential Oil", "AGRO_PLANTATION", "West Coast Plains and Ghats Region (Zone XII)", "TANGEDCO Hill Feeder", ["Udhagamandalam (Ooty)", "Coonoor", "Kotagiri", "Gudalur"], ["Ketti", "Adigaratti", "Nedugula", "Hullathy"], "Kotagiri Tea Gaon", "643217", ["Tea Estate Line", "Toda Tribal Hamlet", "Badaga Hatti"]),
            ("617", "Perambalur", "RURAL", 82.8, "TIER_4", "Small Shallot Onion & Maize Starch Processing", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Agro Rural Feeder", ["Perambalur", "Veppanthattai", "Veppur", "Alathur"], ["Chettikulam", "Kurumbalur", "Valikandapuram", "Padalur"], "Chettikulam Onion Hub", "621104", ["Shallot Onion Farm Colony", "Kudikadu", "Kisan Vasti"]),
            ("618", "Pudukkottai", "RURAL", 80.5, "TIER_3", "Cashew Kernels & Virgin Coconut Oil / Granite", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Feeder", ["Pudukkottai", "Aranthangi", "Alangudi", "Gandarvakottai", "Viralimalai", "Thirumayam", "Ponnamaravathi"], ["Kudumiyanmalai", "Narthamalai", "Kattumavadi", "Illupur"], "Aranthangi Agro Village", "614616", ["Cashew Shelling Basti", "Coconut Yard", "Coastal Fisher Hamlet"]),
            ("619", "Ramanathapuram", "RURAL", 69.7, "TIER_3", "Gundu Dry Red Chilli (Mundu) & Marine Crab/Seaweed Culture", "AGRO_FISHERIES", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Coastal Feeder", ["Ramanathapuram", "Rameswaram", "Paramakudi", "Mudukulathur", "Kamuthi", "Kadaladi", "Thiruvadanai"], ["Sayalgudi", "Devipattinam", "Pamban", "Mandapam Camp"], "Paramakudi Chilli Village", "623707", ["Chilli Drying Yard", "Mundu Farmer Basti", "Kottai Medu"]),
            ("729", "Ranipet", "SEMI_URBAN", 52.3, "TIER_3", "Finished Leather Footwear & Heavy Boiler Auxiliaries", "LEATHER_ENGINEERING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Industrial Feeder", ["Ranipet", "Arcot", "Walajah", "Sholinghur", "Arakkonam", "Nemili"], ["Mukundarayapuram", "Tajpura", "Banavaram", "Kalavai"], "Walajah Leather Gaon", "632513", ["Tannery Artisan Colony", "Shoe Stitchers Line", "Kudil"]),
            ("620", "Salem", "SEMI_URBAN", 48.4, "TIER_2", "Tapioca Sago (Sabudana) Processing & Handloom Silk / Steel", "AGRO_MINERAL", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Sago Agro Feeder", ["Salem", "Attur", "Mettur", "Omalur", "Edappadi", "Sankari", "Yercaud", "Valapady"], ["Mallur", "Attur Rural", "Jalagangapuram", "Sitheri"], "Attur Sago Processing Hub", "636102", ["Sago Factory Colony", "Tapioca Farmer Hamlet", "Weaver Nagar"]),
            ("621", "Sivaganga", "RURAL", 69.2, "TIER_3", "Chettinad Terracotta Pottery & Athangudi Handmade Cement Tiles", "HANDICRAFTS", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Feeder", ["Sivaganga", "Karaikudi", "Devakottai", "Manamadurai", "Ilayangudi", "Kalayarkoil", "Singampunari"], ["Athangudi", "Manamadurai Rural", "Pillayarpatti", "Kandanur"], "Athangudi Tile Artisans Gaon", "630101", ["Athangudi Tile Workshop Lane", "Potters Colony", "Chettinad Vasti"]),
            ("730", "Tenkasi", "RURAL", 58.1, "TIER_3", "Lemon Value Addition & Pattamadai Pai / Sengottai Spices", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Agro Feeder", ["Tenkasi", "Sankarankovil", "Kadayanallur", "Shenkottai", "Alangulam", "Kuruvikulam"], ["Puliyangudi", "Courtrallam Rural", "Surandai", "Sambavar Vadakarai"], "Puliyangudi Lemon Hub", "627855", ["Lemon Market Colony", "Spice Processing Yard", "Kisan Nagar"]),
            ("622", "Thanjavur", "RURAL", 64.6, "TIER_3", "Thanjavur Art Plates, Bronze Sculptures & Paddy Processing", "HANDICRAFTS_AGRO", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Delta Agro Feeder", ["Thanjavur", "Kumbakonam", "Papanasam", "Pattukkottai", "Orathanadu", "Peravurani", "Thiruvaiyaru"], ["Swamimalai", "Nachiyarkoil", "Adirampattinam", "Melattur"], "Swamimalai Bronze Casting Gaon", "612302", ["Sculptors Street (Sthapathi Colony)", "Art Plate Workshop", "Paddy Mill Lane"]),
            ("623", "Theni", "RURAL", 46.2, "TIER_3", "G-9 Cavendish Banana Processing & Cardamom Sorting", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Cardamom & Fruit Feeder", ["Theni", "Periyakulam", "Bodinayakanur", "Uthamapalayam", "Andipatti", "Chinnamanur", "Cumbum"], ["Cumbum Valley Rural", "Devadanapatti", "Kuchanur", "Kombai"], "Bodinayakanur Cardamom Hub", "625513", ["Cardamom Auction Yard Basti", "Banana Packaging Cluster", "Thottam Lane"]),
            ("624", "Thoothukudi", "SEMI_URBAN", 49.9, "TIER_2", "Marine Seafood Cold Chain, Solar Salt Processing & Macaroons", "FISHERIES_FOOD", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Port & Salt Feeder", ["Thoothukudi", "Kovilpatti", "Tiruchendur", "Sathankulam", "Srivaikuntam", "Ottapidaram", "Vilathikulam"], ["Kayalpattinam", "Authoor", "Eral", "Kurumbur"], "Kovilpatti Peanut Candy Village", "628501", ["Chikki Kadalai Mittai Cluster", "Matchbox Artisans Colony", "Kudil"]),
            ("625", "Tiruchirappalli", "SEMI_URBAN", 50.8, "TIER_2", "Grand Naine Banana Processing, Artificial Gems & Heavy Fabrication", "AGRO_FABRICATION", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Trichy Agro & Industrial Feeder", ["Trichy", "Srirangam", "Lalgudi", "Manachanallur", "Musiri", "Thuraiyur", "Thottiyam", "Manapparai"], ["Samayapuram", "Jeeyapuram", "Gunaseelam", "Navalpattu"], "Manachanallur Rice & Banana Gaon", "621005", ["Rice Mill Colony", "Banana Farmer Vasti", "Kudikadu"]),
            ("626", "Tirunelveli", "SEMI_URBAN", 50.1, "TIER_2", "Tirunelveli Wheat Halwa Confectionery & Banana Fiber Extraction", "FOOD_FIBER", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Wind & Solar Feeder", ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Cheranmahadevi", "Nanguneri", "Radhapuram", "Valliyoor"], ["Pattamadai", "Kallidaikurichi", "Mukkudal", "Panagudi"], "Pattamadai Korai Mat Gaon", "627453", ["Korai Silk Mat Weavers Lane", "Halwa Confectionery Yard", "Kisan Basti"]),
            ("731", "Tirupathur", "RURAL", 64.9, "TIER_3", "Vaniyambadi/Ambur Finished Leather Goods & Natrampalli Jaggery", "LEATHER_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Industrial Feeder", ["Tirupathur", "Vaniyambadi", "Ambur", "Natrampalli", "Jolarpet", "Madhanur", "Alangayam"], ["Jolarpettai Rural", "Uthangarai Border", "Pudurnadu", "Yelagiri Hills"], "Ambur Leather Footwear Village", "635802", ["Leather Workshop Lane", "Shoe Upper Artisans Basti", "Kisan Nagar"]),
            ("627", "Tiruppur", "SEMI_URBAN", 38.6, "TIER_1", "Cotton Knitwear, Organic Garments & Kangeyam Coconut Oil", "TEXTILES_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Knitwear Dedicated Power Line", ["Tiruppur", "Avinashi", "Palladam", "Kangeyam", "Dharapuram", "Udumalaipettai", "Madathukulam"], ["Uthukuli Butter Hub", "Kangeyam Rural", "Kunnathur", "Samalapuram"], "Kangeyam Coconut Village", "638701", ["Copra Drying Yard", "Knitwear Stitching Hub", "Kisan Colony"]),
            ("628", "Tiruvallur", "SEMI_URBAN", 35.1, "TIER_2", "Heavy Commercial Vehicles, Engineering Auxiliaries & Dairy", "ENGINEERING_DAIRY", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Industrial Feeder", ["Tiruvallur", "Poonamallee", "Avadi", "Ponneri", "Gummidipoondi", "Uthukottai", "Tiruttani"], ["Periyapalayam", "Kavarapettai", "Thirumazhisai", "Naravarikuppam"], "Gummidipoondi Industrial Gaon", "601201", ["Industrial Auxiliaries Hamlet", "Dairy Cooperative Lane", "Kudikadu"]),
            ("629", "Tiruvannamalai", "RURAL", 79.9, "TIER_3", "Aarni Silk Sarees, Ponni Rice Milling & Cheyyar Automotive", "SILK_AGRO", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Rural Weaver & Agro Feeder", ["Tiruvannamalai", "Arani", "Cheyyar", "Polur", "Chengam", "Vandavasi", "Kilpennathur"], ["Devikapuram", "Vettavalam", "Kannanur", "Nammiyampattu"], "Arani Silk Weaver Gaon", "632301", ["Silk Handloom Weaver Street", "Rice Mill Cluster", "Kisan Basti"]),
            ("630", "Tiruvarur", "RURAL", 79.6, "TIER_4", "Parboiled Rice Milling, Black Gram & Fish Farming", "AGRO_PROCESSING", "East Coast Plains and Hills Region (Zone XI)", "TANGEDCO Delta Agro Feeder", ["Tiruvarur", "Mannargudi", "Thiruthuraipoondi", "Needamangalam", "Nannilam", "Valangaiman"], ["Vaduvur", "Thirumakkottai", "Peralam", "Alathambadi"], "Mannargudi Paddy Village", "614001", ["Paddy Dehusking Mill Lane", "Farmer Kudikadu", "Koil Vattam"]),
            ("631", "Vellore", "SEMI_URBAN", 56.8, "TIER_2", "Vellore Spiny Brinjal Value Addition & Finished Leather Footwear", "AGRO_LEATHER", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Vellore Industrial Feeder", ["Vellore", "Katpadi", "Gudiyatham", "Anaicut", "Kaniyambadi", "Pernambut", "K.V. Kuppam"], ["Bagayam", "Senur", "Paradarami", "Pennathur"], "Katpadi Agro Hub", "632059", ["Brinjal Farmer Cluster", "Tannery Line", "Kisan Nagar"]),
            ("632", "Viluppuram", "RURAL", 85.0, "TIER_3", "Groundnut Oil Processing & Cashew Processing / Terracotta", "AGRO_PROCESSING", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Oil Mills Agro Feeder", ["Viluppuram", "Tindivanam", "Gingee", "Vanur", "Marakkanam", "Vikaravandi", "Kandamangalam"], ["Auroville Rural Fringe", "Gingee Fort Gaon", "Brammadesam", "Ananthapuram"], "Tindivanam Groundnut Oil Hub", "604001", ["Oil Expeller Workshop Colony", "Groundnut Farmer Basti", "Kudil"]),
            ("633", "Virudhunagar", "RURAL", 49.5, "TIER_3", "Sivakasi Printing & Packaging, Safety Matches & Sattur Sev", "PRINTING_FOOD", "Southern Plateau and Hills Region (Zone X)", "TANGEDCO Printing & Agro Feeder", ["Virudhunagar", "Sivakasi", "Sattur", "Rajapalayam", "Aruppukkottai", "Srivilliputhur", "Watrap"], ["Srivilliputhur Palkova Hub", "Alangulam Rural", "Pandalgudi", "Mamsapuram"], "Srivilliputhur Palkova Hub", "626125", ["Palkova Milk Sweet Kitchens", "Printing Press Workers Colony", "Kudil"])
        ]
    }

print("Base setup ready.")
