#!/usr/bin/env python3
"""
Full All-India LGD & ODOP Generator for Gram-Disha.
Generates TypeScript data file `src/data/lgdLocations.ts` containing all 36 States & UTs and all 788+ districts.
"""

import os
import json

def get_all_states_data():
    # 28 States + 8 Union Territories with official districts
    return [
        # 1. Andhra Pradesh (26 districts)
        {
            "stateCode": "28", "stateName": "Andhra Pradesh", "territoryType": "STATE", "totalDistricts": 26,
            "districts": [
                ("502", "Alluri Sitharama Raju", "RURAL", 89.2, "TIER_4", "Organic Coffee & Araku Valley Spices / Pepper", "AGRO_PLANTATION", "East Coast Plains and Hills Region", "APEPDCL Tribal Area Feeder", ["Paderu", "Araku Valley", "Chintapalle", "Rampachodavaram", "Maredumilli"], ["Araku Gaon", "Paderu Rural", "Chintapalle GP"], "Araku Valley Gaon", "531149", ["Coffee Planters Tola", "Tribal Hamlet", "Kisan Nagar"]),
                ("745", "Anakapalli", "SEMI_URBAN", 61.5, "TIER_3", "Anakapalle Jaggery & Agro Derivatives / Food Processing", "AGRO_PROCESSING", "East Coast Plains and Hills Region", "APEPDCL Industrial Feeder", ["Anakapalli", "Chodavaram", "Madugula", "Yellamanchili", "Narsipatnam"], ["Kasimkota", "Munagapaka", "Parawada"], "Anakapalle Jaggery Gaon", "531001", ["Jaggery Market Yard", "Sugarcane Basti", "Kisan Vasti"]),
                ("503", "Ananthapuramu", "RURAL", 72.0, "TIER_3", "Groundnut Oil, Millet Value Addition & Silk Weaving", "AGRO_TEXTILES", "Southern Plateau and Hills Region", "APSPDCL Agro Feeder", ["Anantapur", "Gooty", "Tadipatri", "Uravakonda", "Singanamala"], ["Kalyandurg", "Atmakur", "Bukkarayasamudram"], "Gooty Oil Gaon", "515401", ["Oil Mill Colony", "Groundnut Farmer Basti", "Weaver Lane"]),
                ("746", "Annamayya", "RURAL", 78.4, "TIER_4", "Tomato Paste Processing & Papaya Cultivation / Silk", "AGRO_PROCESSING", "Southern Plateau and Hills Region", "APSPDCL Rural Feeder", ["Rayachoti", "Madanapalle", "Rajampet", "Railway Kodur"], ["Gurramkonda", "Valmikipuram", "Thamballapalle"], "Madanapalle Tomato Hub", "517325", ["Tomato Mandi Area", "Sericulture Hamlet", "Kisan Kudil"]),
                ("747", "Bapatla", "RURAL", 75.3, "TIER_3", "Paddy, Aquaculture & Cashew Processing", "AGRO_FISHERIES", "East Coast Plains and Hills Region", "APCPDCL Coastal Feeder", ["Bapatla", "Chirala", "Repalle", "Vemuru", "Addanki"], ["Vetapalem", "Karamchedu", "Pittalavanipalem"], "Chirala Handloom Gaon", "523155", ["Weavers Street", "Cashew Colony", "Fishermen Basti"]),
                ("504", "Chittoor", "RURAL", 70.5, "TIER_3", "Mango Pulp Processing & Dairy Products / Jaggery", "AGRO_PROCESSING", "Southern Plateau and Hills Region", "APSPDCL Agro Feeder", ["Chittoor", "Palamaner", "Punganur", "Nagari", "GD Nellore"], ["Bangarupalem", "Penumuru", "Gudipala"], "Palamaner Dairy Hub", "517408", ["Dairy Cooperative Basti", "Mango Orchard Line", "Kisan Colony"]),
                ("748", "Dr. B.R. Ambedkar Konaseema", "RURAL", 81.2, "TIER_3", "Coconut Coir Products & Freshwater Aquaculture / Handlooms", "AGRO_FISHERIES", "East Coast Plains and Hills Region", "APEPDCL Delta Feeder", ["Amalapuram", "Razole", "Kothapeta", "Mummidivaram", "Ramachandrapuram"], ["Ravulapalem", "Allavaram", "Malikipuram"], "Amalapuram Coconut Village", "533201", ["Coir Workers Colony", "Prawn Farm Hamlet", "Weavers Lane"]),
                ("505", "East Godavari", "SEMI_URBAN", 58.2, "TIER_2", "Paper Mills, Rice Bran Oil & Food Processing", "AGRO_PROCESSING", "East Coast Plains and Hills Region", "APEPDCL Industrial Feeder", ["Rajahmundry Urban", "Rajahmundry Rural", "Kovvur", "Nidadavole", "Gopalapuram"], ["Kadiam", "Rajanagaram", "Korukonda"], "Kadiam Nursery & Agro Hub", "533126", ["Horticulture Nursery Basti", "Flower Market Line", "Kisan Nagar"]),
                ("749", "Eluru", "RURAL", 76.8, "TIER_3", "Cocoa Processing, Oil Palm Extraction & Carpets", "AGRO_PROCESSING", "East Coast Plains and Hills Region", "APCPDCL Agro Feeder", ["Eluru", "Denduluru", "Chintalapudi", "Nuzvid", "Jangareddigudem"], ["Pedavegi", "Bhimadole", "Polavaram"], "Jangareddigudem Palm Oil Village", "534447", ["Oil Palm Mill Colony", "Cocoa Farmers Basti", "Carpet Weaver Street"]),
                ("506", "Guntur", "SEMI_URBAN", 53.2, "TIER_1", "Guntur Sannam Red Chilli Processing & Cotton Ginning", "AGRO_PROCESSING", "East Coast Plains and Hills Region", "APCPDCL Agro Industrial Feeder", ["Guntur Urban", "Guntur Rural", "Tenali", "Mangalagiri", "Ponnur"], ["Tadikonda", "Medikonduru", "Prathipadu"], "Tenali Agro Food Gaon", "522201", ["Chilli Drying Yard", "Lentil Mill Cluster", "Kisan Colony"]),
                ("750", "Kakinada", "SEMI_URBAN", 51.0, "TIER_2", "Marine Seafood Processing, Rice Exports & Coir", "FISHERIES_AGRO", "East Coast Plains and Hills Region", "APEPDCL Coastal Feeder", ["Kakinada Urban", "Kakinada Rural", "Peddapuram", "Pithapuram", "Tuni"], ["Samalkota", "Karapa", "Thondangi"], "Peddapuram Sago & Agro Hub", "533437", ["Sago Factory Basti", "Seafood Processing Lane", "Kisan Nagar"]),
                ("507", "Krishna", "SEMI_URBAN", 59.4, "TIER_2", "Machilipatnam Kalamkari Handblock Prints & Gold Imitation", "HANDICRAFTS", "East Coast Plains and Hills Region", "APCPDCL Coastal Feeder", ["Machilipatnam", "Gudivada", "Pamarru", "Pedana", "Avanigadda"], ["Challapalli", "Bantumilli", "Kankipadu"], "Pedana Kalamkari Village", "521366", ["Kalamkari Dyeing Workshop", "Weavers Lane", "Fishermen Basti"]),
                ("508", "Kurnool", "SEMI_URBAN", 62.5, "TIER_2", "Onion Dehydration, Cotton Ginning & Cement Minerals", "AGRO_MINERAL", "Southern Plateau and Hills Region", "APSPDCL Industrial Feeder", ["Kurnool", "Adoni", "Yemmiganur", "Kodumur", "Pattikonda"], ["Gudur", "Alur", "Holagunda"], "Yemmiganur Handloom Weavers Gaon", "518360", ["Cotton Weavers Colony", "Onion Mandi Basti", "Kisan Nagar"]),
                ("751", "Nandyal", "RURAL", 74.8, "TIER_3", "Bengal Gram (Chana) Processing & Citrus Fruits", "AGRO_PROCESSING", "Southern Plateau and Hills Region", "APSPDCL Agro Feeder", ["Nandyal", "Allagadda", "Banaganapalle", "Dhone", "Nandikotkur"], ["Mahanandi", "Koilkuntla", "Panyam"], "Banaganapalle Mango & Gram Hub", "518124", ["Mango Orchards Colony", "Dal Mill Cluster", "Kisan Basti"]),
                ("752", "NTR", "SEMI_URBAN", 41.2, "TIER_1", "Kondapalli Wooden Toys & Heavy Vehicle Engineering / Agro", "HANDICRAFTS_ENGINEERING", "East Coast Plains and Hills Region", "APCPDCL Metro Feeder", ["Vijayawada Urban", "Vijayawada Rural", "Mylavaram", "Nandigama", "Jaggayyapeta", "Tiruvuru"], ["Kondapalli", "Ibrahimpatnam", "G.Konduru"], "Kondapalli Toy Artisans Village", "521228", ["Toy Artisans Colony", "Woodcraft Street", "Kisan Nagar"]),
                ("753", "Palnadu", "RURAL", 77.0, "TIER_3", "Cotton Ginning, Chilli Processing & Limestone", "AGRO_MINERAL", "East Coast Plains and Hills Region", "APCPDCL Agro Feeder", ["Narasaraopet", "Sattenapalle", "Vinukonda", "Gurazala", "Macherla", "Chilakaluripet"], ["Piduguralla", "Rentachintala", "Dachepalle"], "Chilakaluripet Cotton Hub", "522616", ["Ginning Mill Compound", "Chilli Drying Floor", "Kisan Basti"]),
                ("754", "Parvathipuram Manyam", "RURAL", 86.5, "TIER_4", "Cashew Processing, Millets & Minor Forest Produce", "AGRO_PROCESSING", "East Coast Plains and Hills Region", "APEPDCL Tribal Agro Feeder", ["Parvathipuram", "Salur", "Kurupam", "Palakonda", "Gummalaxmipuram"], ["Balijipeta", "Seethampeta", "Jiyyammavalasa"], "Kurupam Tribal Millet Village", "535524", ["Cashew Shelling Basti", "Millet Processing Yard", "Tribal Tola"]),
                ("509", "Prakasam", "RURAL", 78.9, "TIER_3", "Tobacco Curing, Granite Tiles & Aquaculture", "AGRO_MINERAL", "East Coast Plains and Hills Region", "APCPDCL Agro Feeder", ["Ongole", "Markapur", "Giddalur", "Kanigiri", "Kandukur", "Darsi"], ["Chimakurthy", "Singarayakonda", "Podili"], "Chimakurthy Granite Hub", "523226", ["Granite Cutting Yard", "Tobacco Barn Colony", "Kisan Basti"]),
                ("510", "Sri Potti Sriramulu Nellore", "SEMI_URBAN", 60.9, "TIER_2", "Aquaculture (Shrimp/Fish) Processing & Somasila Rice", "FISHERIES_AGRO", "East Coast Plains and Hills Region", "APSPDCL Coastal Feeder", ["Nellore Urban", "Nellore Rural", "Kavali", "Gudur", "Atmakur", "Venkatagiri"], ["Venkatagiri Silk Hub", "Indukurpet", "Kovur"], "Venkatagiri Zari Silk Gaon", "524132", ["Zari Handloom Street", "Shrimp Hatchery Basti", "Kisan Colony"]),
                ("755", "Sri Sathya Sai", "RURAL", 78.5, "TIER_4", "Dharmavaram Silk Sarees & Groundnut Processing / Solar", "HANDLOOM_AGRO", "Southern Plateau and Hills Region", "APSPDCL Rural Feeder", ["Puttaparthi", "Dharmavaram", "Kadiri", "Penukonda", "Madakasira"], ["Bukkapatnam", "Gorantla", "Somandepalle"], "Dharmavaram Silk Weaver Village", "515671", ["Silk Loom Sheds", "Groundnut Yard", "Kisan Nagar"]),
                ("511", "Srikakulam", "RURAL", 83.8, "TIER_4", "Ponduru Khadi Handspinning, Cashew & Jute Products", "HANDLOOM_AGRO", "East Coast Plains and Hills Region", "APEPDCL Agro Feeder", ["Srikakulam", "Amadalavalasa", "Narasannapeta", "Tekkali", "Palasa", "Ichchapuram", "Ponduru"], ["Ponduru Khadi GP", "Palasa Cashew GP", "Kotabommali"], "Ponduru Fine Khadi Village", "532168", ["Khadi Spinners Street", "Cashew Processing Yard", "Fishermen Hamlet"]),
                ("756", "Tirupati", "SEMI_URBAN", 58.0, "TIER_2", "Srikalahasti Kalamkari & Electronic Hardware / Agro", "HANDICRAFTS_ELECTRONICS", "Southern Plateau and Hills Region", "APSPDCL Industrial Feeder", ["Tirupati Urban", "Tirupati Rural", "Srikalahasti", "Gudur", "Sullurpeta", "Venkatagiri"], ["Chandragiri", "Renigunta", "Yerpedu"], "Srikalahasti Kalamkari Village", "517644", ["Temple Kalamkari Artisans Colony", "Woodcraft Lane", "Kisan Nagar"]),
                ("512", "Visakhapatnam", "METROPOLITAN", 12.0, "TIER_1", "Marine Fisheries Cold Chain, Heavy Engineering & IT", "FISHERIES_ENGINEERING", "East Coast Plains and Hills Region", "APEPDCL Metro Feeder", ["Gajuwaka", "Bhimunipatnam", "Anandapuram", "Pendurthi", "Padmanabham"], ["Bhimili Coastal GP", "Anandapuram Rural", "Pendurthi Fringe"], "Bhimili Marine Fisher Village", "531163", ["Fishermen Jetty Colony", "Cold Storage Cluster", "Artisan Basti"]),
                ("513", "Vizianagaram", "RURAL", 79.1, "TIER_3", "Jute Twine & Bags, Mango Jelly & Cashew Kernels", "AGRO_PROCESSING", "East Coast Plains and Hills Region", "APEPDCL Agro Feeder", ["Vizianagaram", "Bobbili", "Cheepurupalli", "Gajapathinagaram", "Srungavarapukota"], ["Bobbili Rural", "Nellimarla", "Kothavalasa"], "Bobbili Veena & Jute Village", "535558", ["Musical Instrument Artisans Street", "Jute Mill Colony", "Kisan Nagar"]),
                ("514", "West Godavari", "SEMI_URBAN", 63.8, "TIER_2", "Paddy Milling, Aquaculture & Narsapur Lace Handcrafts", "HANDICRAFTS_AGRO", "East Coast Plains and Hills Region", "APEPDCL Delta Feeder", ["Bhimavaram", "Tadepalligudem", "Tanuku", "Narsapur", "Palakollu"], ["Undi", "Akividu", "Achanta"], "Narsapur Crochet Lace Village", "534275", ["Crochet Lace Workers Street", "Aqua Farm Hamlet", "Kisan Basti"]),
                ("515", "YSR Kadapa", "SEMI_URBAN", 65.0, "TIER_3", "Kadapa Black Stone Slabs, Banana Value Addition & Lime", "MINERAL_AGRO", "Southern Plateau and Hills Region", "APSPDCL Industrial Feeder", ["Kadapa", "Proddatur", "Pulivendula", "Jammalamadugu", "Badvel", "Mydukur"], ["Vempalli", "Yerraguntla", "Kamalapuram"], "Proddatur Gold & Stone Village", "516360", ["Stone Polishers Yard", "Cotton Weavers Line", "Kisan Nagar"])
            ]
        }
    ]

print("Script base defined")
